import Fonts from '../../../Themes/Fonts';
import Colors from '../../../Themes/Colors';

export default {
    generales: {
        flex: 1,
        width: '100%',
        alignItems: 'center', 
        justifyContent: 'center',
    },
    safeArea: {
        flex: 1, 
        width: '100%',
        backgroundColor: '#ffffff',
        margin: 1, 
        alignItems: 'center', 
        justifyContent: 'center',
    },
    contenedor:{
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    contentTop: {
        flex: 1,
        backgroundColor: Colors.$primario,
        height: 120,
        with: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        paddingTop: 35,
        zIndex: 1,
    },
    btnFlechaBack: {
        width: 40, 
        margin: 4,
        position: 'absolute',
        left: 0,
        zIndex: 10,
    },
    btnBack: {
        flexDirection: "row",
        alignItems: 'center', 
        justifyContent: 'center',
        width: 40, 
        height: 30, 
        borderRadius: 10,
        zIndex: 10,
    },
    contentTitle: { 
        flex: 1, 
        width: '100%',
        height: '100%',
        alignItems: 'center',
    },
    title:{
        fontFamily: Fonts.$sizeSubtitle, 
        fontSize: 25, 
        textAlign: 'center', 
        color: '#FFFFFF', 
        marginBottom: 5,
        zIndex: 1,
    },
    subRaya: {
        height: 2, 
        width: 410, 
        backgroundColor: Colors.$primario, 
        alignSelf: 'center',
    },
    contenerod2: {
        width: "100%", 
        height: "100%",
        flex: 1,
    },

    cajaLogo: {
        width: "100%",
        alignItems: 'center',
        marginTop: 50,
    },
    imgtest: {
        width: 90,
        height: 90,
    },
    cajaStarts: {
        width: "100%",
        flexDirection: "row",
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 20,
        marginBottom: 20,
    },
    cajaInput: {
        width: "100%",
        alignItems: 'center',

    },
    inputBeneficios: {
        width: '80%',
        height: 250,
        justifyContent: "flex-start",
        fontSize: 20,
        paddingVertical: 8,
        borderBottomWidth: 1,
        backgroundColor: "transparent",
        paddingLeft: 15,
        marginLeft: 20,
        marginRight: 20,
        borderColor: '#878787',
        borderWidth: 2,
        borderRadius: 25,
        marginTop: 15,
        color: '#878787',
        marginBottom: 30,
    },
    btnCenter: {
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 30,
    },
    buttonNext: {
        flexDirection: "row",
        alignItems: 'center', 
        justifyContent: 'center', 
        backgroundColor: Colors.$primario,
        width: 180, 
        height: 'auto', 
        borderRadius: 25,
        paddingTop: 10,
        paddingBottom: 10,
    },
    btnSaveColor: {
        color: Colors.$blanco,
        fontSize: 20,
    },
}