import Fonts from '../../../Themes/Fonts';
import Colors from '../../../Themes/Colors';
import {Dimensions} from 'react-native';
import {
  horizontalScale,
  moderateScale,
  verticalScale,
} from '../../../Themes/Metrics';

export default {
    generales: {
        flex: 1,
        width: '100%',
        alignItems: 'center', 
        justifyContent: 'center',
    },
    safeArea: {
        flex: 1, 
        width: '100%',
        alignItems: 'center', 
        justifyContent: 'center',
    },
    contenedor:{
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    cajavpmas:{
        position: 'absolute',
        zIndex: 0,
        width: "100%",
        height: "100%",
    },
    
    
    btnBack: {
        flexDirection: "row",
        alignItems: 'center', 
        justifyContent: 'center',
        width: 40, 
        height: 30, 
        borderRadius: 10,
        zIndex: 10,
    },
    contentTitle: { 
        flex: 1, 
        width: '100%',
    },
    title:{
        width: Dimensions.get('window').width*.7,
        fontFamily: Fonts.$sizeSubtitle, 
        fontSize: 20, 
        textAlign: 'center', 
        color: Colors.$texto, 
        backgroundColor: Colors.$blanco,
        marginBottom: 30,
        zIndex: 1,
    },
    boxPrincipalItems: {
        flex: 1,
        width: Dimensions.get("window").width,
        height: Dimensions.get("window").height*.8, 
        marginTop: 30,
        textAlign: 'center',
        alignItems: "center", 
        justifyContent: "center", 
        flexDirection: "row",
        flexWrap: "wrap",
        paddingTop: 30,
        paddingBottom: 30,
        /*shadowColor: Colors.$texto,
        shadowOffset: {
            width: 0,
            height: 3,
        },
        shadowOpacity: 0.29,
        shadowRadius: 4.65,
        elevation: 7,
        marginBottom: 30,*/
    },
    btnVehiculos: {
        width: horizontalScale(120),
        height: verticalScale(120),
        backgroundColor: Colors.$blanco,
        margin: moderateScale(10),
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 18,
        shadowColor: Colors.$texto,
        shadowOffset: {
            width: 0,
            height: 3,
        },
        shadowOpacity: 0.29,
        shadowRadius: 4.65,
        elevation: 7,
    },
    iconBici: {
        width: 50,
        height: 50,
    },
    btnVehiculos2: {
        width: '90%', 
        height: 50,
        backgroundColor: Colors.$primario,
        marginBottom: 30,
        alignSelf: 'center',
        justifyContent: 'center',
        borderRadius: 10,
    },
    btnVehiculosSelect: {
        width: 70, 
        height: 70,
        backgroundColor: '#40CC9A',
        margin: 5,
        alignSelf: 'center',
        justifyContent: 'center',
        borderRadius: 18,
    },
    cajaTextVehiuclos: {
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
    },
    textVehiculo: {
        fontSize: 16,
        color: Colors.$texto,
    },
    cajaImgVP: {
        position: 'absolute',
        right: -5,
        width: 90,
        height: 90,
        borderWidth: 4,
        borderColor: Colors.$blanco,
        borderRadius: 45,
        backgroundColor: Colors.$primario,
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    imgVP: {
        width: 90,
        height: 90,
    },
    btnNext: {
        flexDirection: "row",
        alignItems: 'center', 
        justifyContent: 'center', 
        backgroundColor: Colors.$secundario,
        width: 300, 
        height: 'auto', 
        borderRadius: 25,
        paddingTop: 10,
        paddingBottom: 10,
        marginTop: 5,
        marginBottom: 5,
        zIndex: 200,
    },
    btnReg: {
        flexDirection: "row",
        alignItems: 'center', 
        justifyContent: 'center', 
        backgroundColor: Colors.$primario,
        width: 300, 
        height: 'auto', 
        borderRadius: 25,
        paddingTop: 10,
        paddingBottom: 10,
        marginTop: 5,
        marginBottom: 5,
        zIndex: 100,
    },
    textBtnNext: {
        color: Colors.$blanco,
        fontSize: 16,
    },
    subTitle: {
        fontFamily: Fonts.$sizeSubtitle, 
        fontSize: 22, 
        textAlign: 'center', 
        color: Colors.$secundario,
        marginTop: 30,
        marginBottom: 30,
    },
}