import Fonts from '../../../Themes/Fonts';
import Colors from '../../../Themes/Colors';
import {Dimensions} from 'react-native';
import {
  horizontalScale,
  moderateScale,
  verticalScale,
} from '../../../Themes/Metrics';

export default {
  generales: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  safeArea: {
    backgroundColor: Colors.$blanco,
    alignItems: 'center',
    justifyContent: 'center',
  },
  contenedor: {
    flex: 1,
    width: Dimensions.get('window').width,
    backgroundColor: Colors.$blanco,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
    margin: 0,
  },
  contentTop: {
    backgroundColor: Colors.$blanco,
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: moderateScale(30),
  },
  contentTop2: {
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height,
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'space-around',
    position: 'relative',
    zIndex: 10,
  },
  fondoReserva: {
    position: 'absolute',
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height,
    zIndex: 0,
    top: 0,
  },
  ondaWhite: {
    width: Dimensions.get('window').width,
    height: 60,
    position: 'absolute',
    bottom: 0,
  },
  imgReserva01: {
    width: 300,
    height: 300,
  },
  contenedor2: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: '#fff',
    alignItems: 'center',
  },
  cajas: {
    flex: 1,
    width: '100%',
    flexDirection: 'column',
    alignItems: 'center',
    marginBottom: 10,
  },
  title: {
    fontFamily: Fonts.$montserratExtraBold,
    fontSize: moderateScale(30),
    textAlign: 'center',
    color: Colors.$texto,
    marginBottom: 5,
  },
  contentTitle: {
    flex: 1,
    width: '100%',
  },
  btnBack: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: Dimensions.get('window').width,
    height: 55,
    position: 'absolute',
    left: 0,
    top: 0,
    zIndex: 10,
    backgroundColor: Colors.$primario,
  },
  imgback: {
    width: Dimensions.get('window').width,
    height: 50,
  },
  titleSelect: {
    width: '80%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    fontSize: moderateScale(22),
    fontFamily: Fonts.$montserratExtraBold,
    color: Colors.$texto,
    marginTop: verticalScale(20),
    marginBottom: verticalScale(20),
  },
  titleSelect2: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    fontSize: moderateScale(20),
    fontFamily: Fonts.$montserratExtraBold,
    color: Colors.$texto,
    marginTop: 30,
    marginBottom: 20,
    textShadowColor: Colors.$texto,
    textShadowOffset:{width: 1, height: 1},
    textShadowRadius:1,
  },
  titleSelect3: {
    width: '80%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    fontSize: moderateScale(16),
    fontFamily: Fonts.$montserratExtraBold,
    backgroundColor: Colors.$blanco,
    color: Colors.$texto,
    marginTop: 20,
    marginBottom: 20,
    padding: 10,
    borderRadius: 5,
  },
  itemSelect: {
    backgroundColor: Colors.$primario,
  },
  btnSaveOK: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.$primario,
    width: 350,
    height: 'auto',
    borderRadius: 25,
    padding: 10,
  },
  btnSaveOK2: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.$primario,
    width: 350,
    height: 'auto',
    borderRadius: 25,
    padding: 10,
  },
  btnSaveOK3: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.$texto,
    width: 350,
    height: 'auto',
    borderRadius: 25,
    padding: 10,
  },
  btnSave: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.$texto,
    width: 150,
    height: 'auto',
    borderRadius: 25,
    paddingTop: 10,
    paddingBottom: 10,
    marginRight: 20,
  },
  btnCenter: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 30,
  },
  cajaBtnReservar: {
    marginBottom: 20,
  },
  btnRed: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.$primario,
    width: moderateScale(180),
    height: 'auto',
    borderRadius: 25,
    paddingTop: 10,
    paddingBottom: 10,
  },
  btnTextColorWhite: {
    color: Colors.$blanco,
    fontSize: moderateScale(20),
  },
  btnTextColorBlack: {
    color: Colors.$texto,
    fontSize: moderateScale(20),
    padding: moderateScale(10),
  },
  btnSaveColor: {
    color: Colors.$cuarto,
    fontSize: moderateScale(20),
    textAlign: 'center',
  },
  btnSaveColor2: {
    color: Colors.$blanco,
    fontSize: moderateScale(20),
    textAlign: 'center',
  },
  cajaImgReserva: {
    width: 350,
    height: 350,
    alignSelf: 'center',
    justifyContent: 'center',
  },
  imgReserva: {
    width: '100%',
    height: 350,
  },
  cajaImgGuaya: {
    width: 280,
    height: 280,
    alignSelf: 'center',
    justifyContent: 'center',
  },
  imgGuaya: {
    width: '100%',
    height: '100%',
  },
  msnHorarios: {
    width: 370,
    height: 'auto',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: moderateScale(50),
    fontFamily: Fonts.$size26,
    textAlign: 'center',
  },
  denegado: {
    fontFamily: Fonts.$size26,
    fontSize: moderateScale(20),
    backgroundColor: '#FF7979',
    color: '#fff',
    width: '80%',
    marginBottom: 5,
    paddingLeft: 10,
    borderRadius: 5,
  },
  aceptado: {
    fontFamily: Fonts.$size26,
    fontSize: moderateScale(20),
    color: Colors.$primario,
    marginBottom: 8,
    width: '80%',
    backgroundColor: '#EAEAEA',
    paddingLeft: 10,
    borderRadius: 5,
  },
  textVehiculo: {
    fontSize: moderateScale(24),
    color: Colors.$texto,
  },
  btnVehiculos: {
    width: horizontalScale(60),
    height: verticalScale(90),
    backgroundColor: Colors.$tercer,
    margin: moderateScale(5),
    alignSelf: 'center',
    justifyContent: 'center',
    borderRadius: 18,
  },
  btnVehiculosSelect: {
    width: horizontalScale(60),
    height: verticalScale(100),
    backgroundColor: Colors.$primario,
    margin: 5,
    alignSelf: 'center',
    justifyContent: 'center',
    borderRadius: 18,
    padding: moderateScale(10),
  },
  cajaTextVehiuclos: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconBici: {
    width: horizontalScale(45),
    height: verticalScale(35),
  },
  cajaCuentaRegresiva: {
    flex: 1,
    width: '100%',
    height: 150,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  subcajaCuentaRegresiva: {
    flexDirection: 'column',
    alignItems: 'center',
    backgroundColor: Colors.$primario,
    margin: moderateScale(5),
    padding: moderateScale(10),
    borderRadius: 10,
    marginBottom: verticalScale(20),
  },
  numeroCuentaRegrasiva: {
    fontSize: moderateScale(35),
    color: Colors.$texto,
    fontFamily: Fonts.$montserratExtraBold,
    height: verticalScale(50),
    alignItems: 'center',
    justifyContent: 'center',
    margin: moderateScale(15),
  },
  subtextoCuentaR: {
    fontSize: moderateScale(16),
    textAlign: 'center',
    fontFamily: Fonts.$size22,
    color: Colors.$texto,
  },
  input: {
    width: '100%',
    height: 'auto',
    borderBottomWidth: 1,
    borderColor: '#CCCCCC',
    fontSize: moderateScale(40),
    fontFamily: Fonts.$montserratExtraBold,
    textAlign: 'center',
  },
  aceptado2: {
    fontFamily: Fonts.$size26,
    fontSize: moderateScale(25),
    color: Colors.$blanco,
    marginBottom: 8,
    width: '70%',
    backgroundColor: Colors.$primario,
    paddingLeft: 10,
    borderRadius: 10,
    padding: 5,
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.7,
    shadowRadius: 11.27,
    elevation: 10,
  },

  aceptado3: {
    fontFamily: Fonts.$size26,
    fontSize: moderateScale(25),
    color: Colors.$blanco,
    marginBottom: 8,
    width: '70%',
    backgroundColor: Colors.$texto,
    paddingLeft: 10,
    borderRadius: 10,
    padding: 5,
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.7,
    shadowRadius: 11.27,
    elevation: 10,
  },
  contentMsn: {
    width: '100%',
    height: 'auto',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    paddingLeft: 10,
  },
  boxPrincipalItemsReserva: {
    flex: 1,
    width: Dimensions.get('window').width,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    backgroundColor: Colors.$blanco,
  },
  boxPrincipalItems: {
    flex: 1,
    width: Dimensions.get('window').width,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    backgroundColor: Colors.$tercer,
    borderTopRightRadius: 30,
    borderTopLeftRadius: 30,
    marginLeft: 0,
    marginTop: 20,
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.7,
    shadowRadius: 11.27,
    elevation: -1000,
  },
  fichaReserva: {
    textAlign: 'center',
  },
  textTituloClave3: {
    color: 'black',
    fontSize: moderateScale(20),
  },
  vpsoporte: {
    width: horizontalScale(60),
    height: verticalScale(70),
  },
  cajaImgVP: {
    position: 'absolute',
    width: 200,
    height: 200,
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 100
  },
  imgVP: {
      width: 200,
      height: 200,
  },
};
