import Fonts from '../../../Themes/Fonts';
import Colors from '../../../Themes/Colors';
import {Dimensions} from 'react-native';
import {
  horizontalScale,
  moderateScale,
  verticalScale,
} from '../../../Themes/Metrics';

export default {
  generales: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  safeArea: {
    flex: 1,
    backgroundColor: Colors.$parqueo_color_fondo,
    alignItems: 'center',
    justifyContent: 'center',
  },
  contenedor: {
    width: Dimensions.get('window').width,
    position: 'relative',
    padding: 0,
    marginTop: 0,
    backgroundColor: Colors.$parqueo_color_fondo,
    alignItems: 'center'
  },
  contentTop: {
    backgroundColor: Colors.$blanco,
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: moderateScale(10),
    height: 'auto',
    marginTop: 50
  },
  contentTop2: {
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height,
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'space-around',
    position: 'relative',
    zIndex: 10,
  },
  fondoReserva: {
    position: 'absolute',
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height,
    zIndex: 0,
    top: 0,
  },
  ondaWhite: {
    width: Dimensions.get('window').width,
    height: 60,
    position: 'absolute',
    bottom: 0,
  },
  imgReserva01: {
    width: 300,
    height: 300,
  },
  contenedor2: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: '#fff',
    alignItems: 'center',
  },
  cajas: {
    flex: 1,
    width: '100%',
    flexDirection: 'column',
    alignItems: 'center',
    marginBottom: 10,
  },
  title: {
    fontFamily: Fonts.$montserratExtraBold,
    fontSize: moderateScale(24),
    textAlign: 'center',
    color: Colors.$parqueo_color_texto,
    marginTop: 50,
  },
  contentTitle: {
    flex: 1,
    width: '100%',
  },
  btnBack: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: Dimensions.get('window').width,
    height: 55,
    position: 'absolute',
    left: 0,
    top: 0,
    zIndex: 10,
    backgroundColor: Colors.$primario,
  },
  imgback: {
    width: Dimensions.get('window').width,
    height: 50,
  },
  titleSelect: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    fontSize: 20,
    fontFamily: Fonts.$poppinsregular,
    color: Colors.$texto,
    marginTop: 20,
    marginBottom: 20,
    zIndex: 1000
  },
  titleSelect2: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    fontSize: 20,
    fontFamily: Fonts.$montserratExtraBold,
    color: Colors.$texto,
    marginTop: 5,
    marginBottom: 30,
    textShadowColor: Colors.$texto,
    textShadowOffset:{width: 1, height: 1},
    textShadowRadius:1,
  },
  titleSelect3: {
    width: '80%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    fontSize: moderateScale(16),
    fontFamily: Fonts.$montserratExtraBold,
    backgroundColor: Colors.$blanco,
    color: Colors.$texto,
    marginTop: 20,
    marginBottom: 20,
    padding: 10,
    borderRadius: 5,
  },
  titleSelect4: {
    width: '60%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    fontSize: 18,
    fontFamily: Fonts.$poppinsregular,
    color: Colors.$parqueo_color_texto,
  },
  itemSelect: {
    backgroundColor: Colors.$primario,
  },
  btnSaveOK: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.$primario,
    width: 350,
    height: 'auto',
    borderRadius: 25,
    padding: 10,
  },
  btnSaveOK2: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.$primario,
    width: 350,
    height: 'auto',
    borderRadius: 25,
    padding: 10,
  },
  btnSaveOK3: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.$texto,
    width: 350,
    height: 'auto',
    borderRadius: 25,
    padding: 10,
  },
  btnSave: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.$texto,
    width: 150,
    height: 'auto',
    borderRadius: 25,
    paddingTop: 10,
    paddingBottom: 10,
    marginRight: 20,
  },
  btnCenter: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
    backgroundColor: Colors.$parqueo_color_adicional,
    borderRadius: 25
  },
  cajaBtnReservar: {
    marginBottom: 20,
    backgroundColor: Colors.$parqueo_color_fondo,
    padding: 10,
    alignItems: 'center',
    justifyContent: 'center'
  },
  btnRed: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: 150,
    height: 'auto',
    borderRadius: 20,
  },
  btnBlack: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.$texto,
    width: moderateScale(180),
    height: 'auto',
    borderRadius: 25,
  },
  btnTextColorWhite: {
    color: Colors.$blanco,
    fontSize: 20,
  },
  btnTextColorBlack: {
    color: Colors.$negro,
    fontFamily: Fonts.$poppinsregular,
    fontSize: 20,
    padding: 10,
  },
  btnSaveColor: {
    color: Colors.$texto,
    fontSize: 20,
    textAlign: 'center',
  },
  btnSaveColor2: {
    color: Colors.$blanco,
    fontSize: 20,
    textAlign: 'center',
  },
  cajaImgReserva: {
    width: 350,
    height: 'auto',
    alignSelf: 'center',
    justifyContent: 'center',
  },
  imgReserva: {
    width: '100%',
    height: 350,
  },
  cajaImgGuaya: {
    width: 280,
    height: 280,
    alignSelf: 'center',
    justifyContent: 'center',
  },
  imgGuaya: {
    width: '100%',
    height: '100%',
  },
  msnHorarios: {
    width: 370,
    height: 'auto',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: moderateScale(50),
    fontFamily: Fonts.$size26,
    textAlign: 'center',
  },
  denegado: {
    fontFamily: Fonts.$size26,
    fontSize: moderateScale(16),
    backgroundColor: Colors.$tercer,
    color: Colors.$parqueo_color_adicional,
    width: '100%',
    marginBottom: 5,
    padding: 10,
    borderRadius: 5,
    textAlign: 'center'
  },
  aceptado: {
    fontFamily: Fonts.$size26,
    fontSize: 20,
    color: Colors.$primario,
    marginBottom: 8,
    width: '80%',
    backgroundColor: '#EAEAEA',
    paddingLeft: 10,
    borderRadius: 5,
  },
  textVehiculo: {
    fontSize: 20,
    color: Colors.$parqueo_color_texto_50,
  },
  btnVehiculos: {
    width: 120,
    height: 85,
    margin: 5,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: Colors.$parqueo_color_texto_50,
    borderWidth: 4,
    borderStyle: 'dashed'
  },
  btnVehiculosSelect: {
    width: 120,
    height: 85,
    margin: 5,
    alignItems: 'center',
    justifyContent: 'center',    
    borderColor: Colors.$parqueo_color_adicional,
    borderWidth: 4,
    borderStyle: 'dashed'
  },
  cajaTextVehiuclosDisponible: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    width: 90,
    height: 90,
    borderRadius: 10,
    backgroundColor: Colors.$disponible,
  },
  cajaTextVehiuclosReservada: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    width: 90,
    height: 90,
    borderRadius: 10,
    backgroundColor: Colors.$reservada
  },
  cajaTextVehiuclosPrestada: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    width: 90,
    height: 90,
    borderRadius: 10,
    backgroundColor: Colors.$prestada
  },
  cajaTextVehiuclosInactiva: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    width: 90,
    height: 90,
    borderRadius: 10,
    backgroundColor: Colors.$inactiva
  },
  cajaTextVehiuclosTaller: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    width: 90,
    height: 90,
    borderRadius: 10,
    backgroundColor: Colors.$taller
  },
  cajaTextVehiuclosSinEstado: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    width: 90,
    height: 90,
    borderRadius: 10,
    backgroundColor: 'white'
  },
  iconBici: {
    width: 40,
    height: 40,
    color: Colors.$blanco
  },
  cajaCuentaRegresiva: {
    flex: 1,
    width: '100%',
    height: 150,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  subcajaCuentaRegresiva: {
    flexDirection: 'column',
    alignItems: 'center',
    backgroundColor: Colors.$texto,
    margin: 5,
    padding: 10,
    borderRadius: 10,
    marginBottom: 20,
    height: 70,
    justifyContent: 'center',
  },
  numeroCuentaRegrasiva: {
    fontSize: 20,
    color: Colors.$blanco,
    fontFamily: Fonts.$poppinsregular,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    margin: 10,
  },
  subtextoCuentaR: {
    fontSize: 10,
    textAlign: 'center',
    fontFamily: Fonts.$poppinsregular,
    color: Colors.$blanco,
  },
  input: {
    width: '100%',
    height: 'auto',
    borderBottomWidth: 1,
    borderColor: '#CCCCCC',
    fontSize: moderateScale(40),
    fontFamily: Fonts.$montserratExtraBold,
    textAlign: 'center',
  },
  aceptado2: {
    fontFamily: Fonts.$size26,
    fontSize: moderateScale(25),
    color: Colors.$blanco,
    marginBottom: 8,
    width: '70%',
    backgroundColor: Colors.$primario,
    paddingLeft: 10,
    borderRadius: 10,
    padding: 5,
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.7,
    shadowRadius: 11.27,
    elevation: 10,
  },

  aceptado3: {
    fontFamily: Fonts.$size26,
    fontSize: moderateScale(25),
    color: Colors.$blanco,
    marginBottom: 8,
    width: '70%',
    backgroundColor: Colors.$texto,
    paddingLeft: 10,
    borderRadius: 10,
    padding: 5,
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.7,
    shadowRadius: 11.27,
    elevation: 10,
  },
  contentMsn: {
    width: '100%',
    height: 'auto',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 100,
    paddingLeft: 10,
  },
  boxPrincipalItemsReserva: {
    flex: 1,
    width: Dimensions.get('window').width*.8,
    minHeight: Dimensions.get('window').height*.6,
    alignItems: 'center',
    justifyContent: 'space-around',
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingTop: 20,
    marginBottom: 100
  },
  boxPrincipalItems: {
    flex: 1,
    width: Dimensions.get('window').width,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    backgroundColor: Colors.$tercer,
    borderTopRightRadius: 30,
    borderTopLeftRadius: 30,
    marginLeft: 0,
    marginTop: 20,
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.7,
    shadowRadius: 11.27,
    elevation: -1000,
  },
  fichaReserva: {
    textAlign: 'center',
  },
  textTituloClave3: {
    color: 'black',
    fontSize: 20,
  },
  vpsoporte: {
    width: horizontalScale(40),
    height: verticalScale(40),
  },
  cajaImgVP: {
    position: 'absolute',
    width: 200,
    height: 200,
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 100,
    marginBottom:50
  },
  imgVP: {
    width: 220,
    height: 220,
    borderRadius: 100,
  },
  botonItem: {
    backgroundColor: Colors.$primario,
    width: "100%",
    height: "auto",
    alignItems: "left",
    justifyContent: "center",
    padding: 10
  },
  textBoton: {
    fontSize: 20,
  },
  DISPONIBLE: {
    backgroundColor: 'red'
  }
};
