import Fonts from '../../../Themes/Fonts';
import Colors from '../../../Themes/Colors';

export default {
    contenedor:{
        backgroundColor: 'rgba(255, 255, 255, 1)', 
        marginLeft: 0,
        marginRight: 0,
    },
    contentTop: {
        backgroundColor: Colors.$primario,
        height: 'auto',
        with: '100%',
    },
    inputText: {
        width: 250,
        justifyContent: 'center',
        alignItems: 'center',
    },
    contentImg: {
        width: '100%',
        height: 200,
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    ziseImg: {
        width: 200,
        height: 100,
    },
    contentImg2: {
        width: '100%',
        height: 300,
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    ziseImg2: {
        width: 200,
        height: 200,
    },
   
    inputText: {
        fontFamily: Fonts.$sizeSubtitle, 
        fontSize: 20, 
        textAlign: 'left', 
        color: '#878787', 
        paddingLeft: 10,
    },
    contenedor2:{
        flex: 1,
        flexDirection: 'column',
        backgroundColor: "#fff",
        width: "100%",
        height: "100%",
        alignItems: 'center'
      },
      cajas:{
        flex: 1,
        width: '100%',
        flexDirection: 'column',
        alignItems: 'center',
        marginBottom: 50,
      },
      botones:{
        flexDirection: 'row',
        alignItems: 'center',
      },
      botonTiempo:{
        backgroundColor: "#40CC9A",
        width: 60,
        height: 60,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 50,
        marginLeft: 5,
        marginTop: 20,
      },
      botonTiempoGris:{
        backgroundColor: "#C1C6C1",
        width: 60,
        height: 60,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 50,
        marginLeft: 5,
        marginTop: 20,
      },
      letraTiempo:{
        color: '#fff',
        fontSize: 22,
      },
      letraTiempoGris:{
        color: '#000',
        fontSize: 22,
      },
      inputBeneficios: {
        width: '80%',
        height: 150,
        justifyContent: "flex-start",
        fontSize: 20,
        paddingVertical: 8,
        borderBottomWidth: 1,
        backgroundColor: "#c3c3c3",
        paddingLeft: 15,
        marginLeft: 20,
        marginRight: 20,
        borderColor: '#c3c3c3',
        borderWidth: 2,
        borderRadius: 25,
        marginTop: 15,
        color: '#000000',
        marginBottom: 30,
      },
    title:{
        fontFamily: Fonts.$sizeTitle, 
        fontSize: 25, 
        textAlign: 'center', 
        color: '#FFFFFF', 
        marginBottom: 5
    },
    title2:{
        fontFamily: Fonts.$montserratExtraBold, 
        fontSize: 24, 
        textAlign: 'center', 
        color: '#878787', 
        marginBottom: 5
    },
    contentTitle: { 
        flex: 1, 
        width: '100%',
    },
    btnBack: {
        flexDirection: "row",
        alignItems: 'center', 
        justifyContent: 'center',
        width: 40, 
        height: 30, 
        borderRadius: 10,
    },
    safeArea: {
        flex: 1, 
        width: '100%',
        height: '100%',
        backgroundColor: Colors.$blanco,
        alignItems: 'center', 
        justifyContent: 'center',
    },
    titleSelect: {
        width: '100%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: 22,
        textAlign: 'center',
        fontFamily: Fonts.$size26,
        color: '#878787', 
        marginTop: 20,
    },
    itemSelect: {
        backgroundColor: '#40CC9A',
    },
    btnSave: {
        flexDirection: "row",
        alignItems: 'center', 
        justifyContent: 'center', 
        backgroundColor: '#EAEAEA',
        width: 180, 
        height: 'auto', 
        borderRadius: 25,
        paddingTop: 10,
        paddingBottom: 10,
    },
    btnCenter: {
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 30,
        marginBottom: 30,
    },
    btnSaveColor: {
        color: Colors.$blanco,
        fontSize: 16,
    },
    btnSaveColor3: {
        color: '#ffffff',
        fontSize: 16,
        textAlign: 'center',
    },
    cajaImgReserva: {
        width: 350,
        height: 350,
        alignSelf: 'center',
        justifyContent: 'center',
    },
    imgReserva: {
        width: '100%',
        height: 350,
    },
    cajaImgGuaya: {
        width: 280,
        height: 280,
        alignSelf: 'center',
        justifyContent: 'center',
    },
    imgGuaya: {
        width: '100%',
        height: '100%',
    },
    msnHorarios: {
        width: 370,
        height: 'auto',
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: 50, 
        fontFamily: Fonts.$size26,
        textAlign: 'center', 
    },
    denegado: {
        fontFamily: Fonts.$size26,
        fontSize: 20,
        backgroundColor: '#FF7979',
        color: '#fff',
        width: '80%',
        marginBottom: 5,
        paddingLeft: 10,
        borderRadius: 5,
    },
    aceptado: {
        fontFamily: Fonts.$size26,
        fontSize: 20,
        color: '#40CC9A',
        marginBottom: 8,
        width: '80%',
        backgroundColor: '#EAEAEA',
        paddingLeft: 10,
        borderRadius: 5,
    },
    cajaTextVehiuclos: {
        flex: 1,
        alignItems: "center", 
        justifyContent: "center",
    },
    textVehiculo: {
        fontSize: 28,
        color: "black",
    },
    btnVehiculos: {
        width: 70, 
        height: 70,
        backgroundColor: '#CCCCCC',
        margin: 5,
        alignSelf: 'center',
        justifyContent: 'center',
        borderRadius: 18,
    },
    btnVehiculosSelect: {
        width: 70, 
        height: 70,
        backgroundColor: '#40CC9A',
        margin: 5,
        alignSelf: 'center',
        justifyContent: 'center',
        borderRadius: 18,
    },
    cajaCuentaRegresiva: {
        flex: 1,
        width: '100%', 
        height: 'auto',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    subcajaCuentaRegresiva: {
        flex: 1,
        flexDirection: 'column',
        alignItems: 'center',
        backgroundColor: '#EAEAEA',
        marginRight: 5,
        marginLeft: 5,
        borderRadius: 10,
    },
    numeroCuentaRegrasiva: {
        fontSize: 25,
        color: '#40CC9A',
        fontFamily: Fonts.$montserratLight2,
    },
    subtextoCuentaR: {
        width: '100%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: 16,
        textAlign: 'center',
        fontFamily: Fonts.$size22,
        color: '#ffffff',
        backgroundColor: '#40CC9A',
    },
    generales: {
        flex: 1,
        width: '100%',
        alignItems: 'center', 
        justifyContent: 'center',
    },
    
    
    contentCenter: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    }, 
    btnSaveOK: {
        flexDirection: "row",
        alignItems: 'center', 
        justifyContent: 'center', 
        backgroundColor: Colors.$primario,
        width: 180, 
        height: 'auto', 
        borderRadius: 25,
        paddingTop: 10,
        paddingBottom: 10,
    },
    btnSI: {
        flex: 1,
        flexDirection: "row",
        alignItems: 'center', 
        justifyContent: 'center', 
        backgroundColor: '#40CC9A',
        width: 50, 
        height: 50, 
        borderRadius: 25,
        paddingTop: 10,
        paddingBottom: 10,
    },
    btnAntes: {
        flex: 1,
        flexDirection: "row",
        alignItems: 'center', 
        justifyContent: 'center', 
        backgroundColor: '#EAEAEA',
        width: 50, 
        height: 50, 
        borderRadius: 25,
        paddingTop: 10,
        paddingBottom: 10,
    },
    btnCancelar: {
        flex: 1,
        flexDirection: "row",
        alignItems: 'center', 
        justifyContent: 'center', 
        backgroundColor: '#FD6B6B',
        width: 180, 
        height: 'auto', 
        borderRadius: 25,
        paddingTop: 10,
        paddingBottom: 10,
    },
    
    btnSaveColor2: {
        color: '#878787',
        fontSize: 20,
        
    },
    aceptado2: {
        fontFamily: Fonts.$size26,
        fontSize: 24,
        color: '#fff',
        marginBottom: 8,
        width: '90%',
        backgroundColor: '#40CC9A',
        paddingLeft: 10,
        borderRadius: 5,
    },
    contentMsn: {
        width: '100%', 
        height: 'auto',
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 10,
        paddingLeft: 10,
    },
    fichaReserva:{
        width: '100%', 
        height: 'auto',
        flex: 1,
        alignItems: 'flex-start',
        justifyContent: 'center',
        marginTop: 10,
        paddingLeft: 10,
    },
    cajaCod: {
        flex: 1,
        width: '100%',
        alignItems: 'center',
        justifyContent: 'center',
    },
    
    textTituloClave: {
        fontFamily: Fonts.$size22,
        color: '#878787',
    },
    textTituloClave2: {
        fontFamily: Fonts.$size26,
        fontSize: 20,
        color: '#40CC9A', 
        padding: 10,
    },
    textTituloClave3: {
        fontFamily: Fonts.$size22,
        color: '#878787',
        fontSize: 22,
    },
    textTituloClave4: {
        fontFamily: Fonts.$size22,
        color: '#878787',
        fontSize: 20,
    },
    textClave: {
        fontFamily: Fonts.$montserratExtraBold,
        fontSize: 50,
        marginTop: 10,
        marginBottom: 10,
    },
    boxPrincipalItems: {
        flex: 1,
        width: '100%',
        alignItems: "center", 
        justifyContent: "center", 
        flexDirection: "row",
        flexWrap: "wrap",
        padding: 20,
    },
    boxPrincipalItems2: {
        width: '90%',
        alignItems: "center", 
        justifyContent: "center", 
        flexDirection: "row",
        flexWrap: "wrap",
        padding: 20, 
    },
    boxPrincipalItems3: {
        width: '100%',
        alignItems: "center", 
        justifyContent: "center", 
        flexDirection: "row",
        flexWrap: "wrap",
        padding: 20, 
    },
    cajaBtnRentar: {
        width: '100%',
        marginTop: 5,
        marginBottom: 5,
        flex: 1,
        flexDirection: 'row', 
        justifyContent: 'center',
        alignItems: 'center',
        flexWrap: 'nowrap',
    },
    map: {
        flex: 1,
        width: '100%',
        height: 400,
    },
    textoInput: {
        width: '100%',
        backgroundColor: '#cecece',
    },
}