import Fonts from '../../../Themes/Fonts';
import Colors from '../../../Themes/Colors';

export default {
    contenedor:{
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    cajavpmas:{
        position: 'absolute',
        zIndex: 0,
        width: "100%",
        height: "100%",
    },
    subRaya: {
        height: 2, 
        width: 410, 
        backgroundColor: Colors.$primario, 
        alignSelf: 'center',
    },
    btnFlechaBack: {
        width: 40, 
        margin: 4,
        position: 'absolute',
        left: 0,
        zIndex: 10,
    },
    contentTop: {
        flex: 1,
        backgroundColor: Colors.$primario,
        height: 60,
        with: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        paddingTop: 15,
        zIndex: 1,
    },
    generales: {
        flex: 1,
        width: '100%',
        alignItems: 'center', 
        justifyContent: 'center',
    },
    safeArea: {
        flex: 1, 
        width: '100%',
        backgroundColor: '#ffffff',
        margin: 1, 
        alignItems: 'center', 
        justifyContent: 'center',
    },
    btnBack: {
        flexDirection: "row",
        alignItems: 'center', 
        justifyContent: 'center',
        width: 40, 
        height: 30, 
        borderRadius: 10,
        zIndex: 10,
    },
    contentTitle: { 
        flex: 1, 
        width: '100%',
    },
    title:{
        fontFamily: Fonts.$sizeSubtitle, 
        fontSize: 25, 
        textAlign: 'center', 
        color: '#FFFFFF', 
        marginBottom: 5,
        zIndex: 1,
    },
    boxPrincipalItems: {
        flex: 1,
        width: '80%',
        marginTop: 30,
        borderRadius: 10,
        backgroundColor: Colors.$blanco,
        textAlign: 'center',
        alignItems: "center", 
        justifyContent: "center", 
        flexDirection: "row",
        flexWrap: "wrap",
        paddingTop: 30,
        paddingBottom: 30,
        shadowColor: Colors.$texto,
        shadowOffset: {
            width: 0,
            height: 3,
        },
        shadowOpacity: 0.29,
        shadowRadius: 4.65,
        elevation: 7,
        marginBottom: 30,
    },
    btnVehiculos: {
        width: '90%', 
        height: 50,
        backgroundColor: Colors.$secundario,
        marginBottom: 50,
        alignSelf: 'center',
        justifyContent: 'center',
        borderRadius: 10,
    },
    btnVehiculos2: {
        width: '90%', 
        height: 50,
        backgroundColor: Colors.$primario,
        marginBottom: 50,
        alignSelf: 'center',
        justifyContent: 'center',
        borderRadius: 10,
    },
    btnVehiculosSelect: {
        width: 70, 
        height: 70,
        backgroundColor: '#40CC9A',
        margin: 5,
        alignSelf: 'center',
        justifyContent: 'center',
        borderRadius: 18,
    },
    cajaTextVehiuclos: {
        flex: 1, 
        justifyContent: "center",
    },
    textVehiculo: {
        fontSize: 20,
        color: Colors.$blanco,
        paddingLeft: 20,
    },
    cajaImgVP: {
        position: 'absolute',
        right: -5,
        width: 90,
        height: 90,
        borderWidth: 4,
        borderColor: Colors.$blanco,
        borderRadius: 45,
        backgroundColor: Colors.$primario,
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    imgVP: {
        width: 90,
        height: 90,
    },
    btnNext: {
        flexDirection: "row",
        alignItems: 'center', 
        justifyContent: 'center', 
        backgroundColor: Colors.$secundario,
        width: 250, 
        height: 'auto', 
        borderRadius: 25,
        paddingTop: 10,
        paddingBottom: 10,
        marginTop: 5,
        marginBottom: 5,
        zIndex: 200,
    },
    btnReg: {
        flexDirection: "row",
        alignItems: 'center', 
        justifyContent: 'center', 
        backgroundColor: Colors.$primario,
        width: 250, 
        height: 'auto', 
        borderRadius: 25,
        paddingTop: 10,
        paddingBottom: 10,
        marginTop: 5,
        marginBottom: 5,
        zIndex: 100,
    },
    textBtnNext: {
        color: '#ffffff',
        fontSize: 20,
    },
}