import Fonts from '../../../Themes/Fonts';
import Colors from '../../../Themes/Colors';
import { Dimensions } from 'react-native';

export default {
    contenedor:{
        flex: 1,
        width: "100%",
        height: "100%",
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: Colors.$primario,
    },
    subRaya: {
        height: 2, 
        width: 410, 
        backgroundColor: 'transparent', 
        alignSelf: 'center',
    },
    btnFlechaBack: {
        width: 40, 
        margin: 4,
        position: 'absolute',
        left: 0,
        zIndex: 10,
    },
    contentTop: {
        flex: 1,
        backgroundColor: Colors.$primario,
        height: 60,
        with: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        paddingTop: 10,
    },    
    contenedorQR: {
        flex: 1,
        flexDirection: 'column', 
        justifyContent: 'center',
        alignItems: 'center',
        overflow: 'hidden',
        width: 350,
        height: 650,
    },
    cajaQR: {
        width: 350,
        height: 650,
    },
    centerText: {
        flex: 1,
        fontSize: 16,
        zIndex: 10,
    },
    textBold: {
        fontWeight: '300',
        color: '#000'
    },
    buttonText: {
        fontSize: 21,
        color: 'rgb(0,122,255)'
    },
    buttonTouchable: {
        flexDirection: "row",
        alignItems: 'center', 
        justifyContent: 'center', 
        backgroundColor: Colors.$primario,
        width: 180, 
        height: 'auto', 
        borderRadius: 25,
        paddingTop: 10,
        paddingBottom: 10,
    },
    buttonNext: {
        flexDirection: "row",
        alignItems: 'center', 
        justifyContent: 'center', 
        backgroundColor: '#878787',
        width: 180, 
        height: 'auto', 
        borderRadius: 25,
        paddingTop: 10,
        paddingBottom: 10,
    },
    divInput: {
        width: 300,
        backgroundColor: '#fff',
        borderRadius: 0,
        marginBottom: 10,
        marginTop: 20,
        borderWidth: 4,
        borderColor: "red",
    },
    input:{
        width: '100%',
        height: 'auto',
        borderColor: Colors.$primario,
        borderWidth: 4,
        fontSize: 20,
        fontFamily: Fonts.$size26,
        textAlign: 'center',
    },
    //cronometro
    container: {
        flex: 1,
        backgroundColor: '#fff',
        alignItems: 'center', 
        justifyContent: 'center',
    },
    map: {
        flex: 1,
        width: 350,
        height: 500,
    },
    cajabotones: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
        marginBottom: 10,
        marginTop: 10
    },
    cajainformacion: {
        flex: 1,
        flexDirection: 'column',
    },
    cajaIndicadores: {
        flex: 1,
        width: 250,
        alignItems: "center", 
        justifyContent: "center", 
        flexDirection: "row",
        flexWrap: "wrap",
        position: "absolute",
        left: 0,
        bottom: 220,
        zIndex: 100,
    },
    cajaIndicadoresTrip: {
        flex: 1,
        width: Dimensions.get("window").width,
        height: Dimensions.get("window").height*0.7, 
        alignItems: "center", 
        justifyContent: "center", 
        flexDirection: "column",
        flexWrap: "wrap",
    },
    cajaSubIn: {
        flex: 1,
        width: Dimensions.get("window").width,
        alignItems: "center",
        justifyContent: "center",
    },
    subIndicadores: {
        width: 120, 
        height: 120,
        backgroundColor: Colors.$primario,
        margin: 5,
        alignItems: "center",
        justifyContent: 'center',
        borderRadius: 60,
        flexDirection: 'column',
        zIndex: 8,
    },
    textsubIndicadures:{
        color: Colors.$cuarto,
        fontSize: 18,
        fontFamily: 'bold',
    },
    cajaBtnTerminar:{
        width: "100%",
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 10,
        marginBottom: 10,
    },
    botonTerminarViaje: {
        backgroundColor: 'white',
        paddingLeft: 20,
        paddingRight: 20,
        borderRadius: 15,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 3,
        },
        shadowOpacity: 0.5,
        shadowRadius: 4.65,
        elevation: 7,
        borderColor: Colors.$primario,
        borderWidth: 2,
    },
    btnTextoTerminarViaje: {
        color: '#878787',
        fontSize: 20,
        fontFamily: 'bold',
    },
    botonPausarViaje: {
        backgroundColor: 'yellow',
        padding: 10,
        borderRadius: 15,
    },
    btnTextoPausarViaje: {
        color: '#fff',
        fontSize: 25,
        fontFamily: 'bold',
    },
    botonIniciarViaje: {
        backgroundColor: Colors.$primario,
        padding: 10,
        borderRadius: 15,
        position: 'absolute',
        bottom: 100,
        right: 10,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 3,
        },
        shadowOpacity: 0.5,
        shadowRadius: 4.65,
        elevation: 7,
    },
    botonIniciarViaje2: {
        backgroundColor: Colors.$primario,
        padding: 10,
        borderRadius: 15,
        position: 'relative',
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 3,
        },
        shadowOpacity: 0.5,
        shadowRadius: 4.65,
        marginTop: 20,
    },
    btnTextoIniciarViaje: {
        color: '#fff',
        fontSize: 20,
        fontFamily: 'bold',
    },
    //end cronometro
    //map
    map: {
        flex: 1,
        width: '100%',
        height: 570,
    },
    //end map
    cajaIndicadoresClima: {
        width: "100%",
        height: "100%",
        flex: 1,
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "center",
        zIndex: 1,
        paddingTop: 20,
        paddingBottom: 20,
        borderRadius: 30,
        backgroundColor: "white",
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 3,
        },
        shadowOpacity: 0.5,
        shadowRadius: 4.65,
        elevation: 7,
    },
    cajaclima: {
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#f8f7f5",
        padding: 5,
        borderRadius: 10,
    },
    itemClima: {
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        marginRight: 10,
    },
    imgClima: {
        width: 50,
        height: 30,
    },
    textClima: {
        fontSize: 18,
    },
    cajalogo: {
        width: "100%",
        flex: 1,
        alignItems: "center",
        textAlign: "center",
        justifyContent: "center",
        marginTop: 20,
        marginBottom: 20,
    },
    cajalogo2: {
        width: "100%",
        height: 200,
        flex: 1,
        alignItems: "center",
        marginTop: 40,
        marginBottom: 40,
        backgroundColor: Colors.$blanco
    },
    logocolor: {
        width: "80%",
        height: "100%",
    },
    resumen: {
        width: 40,
        height: 40,
        marginTop: 40,
    },
    letraResumen: {
        color: Colors.$texto,
        fontFamily: Fonts.$montserratMedium,
        fontSize: 22,
    },
    cajaDatosResumen: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-evenly',
        width: '100%',
        height: 120,
    },
    vpkm: {
        width: 60,
        height: 40,
    },
    cajaDatosItem: {
        width: 100,
        height: 100,
        backgroundColor: Colors.$tercer,
        borderRadius: 10,
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
    },
    letrablanca: {
        color: Colors.$blanco,
        fontFamily: Fonts.$montserratLight,
        fontSize: 14,
    },
    letranegra: {
        color: Colors.$texto,
        fontFamily: Fonts.$montserratLight,
        fontSize: 14,
    },
    cajaSoporte: {
        width: "100%",
        height: 500,
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
    },
    vpsoporte: {
        width: 80,
        height: 80,
    },
    btnSoporte: {
        backgroundColor: Colors.$primario,
        width: 200,
        height: 40,
        justifyContent: 'center',
        alignItems: "center",
        paddingLeft: 20,
        paddingRight: 20,
        borderRadius: 10,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 3,
        },
        shadowOpacity: 0.5,
        shadowRadius: 4.65,
        elevation: 7,
        borderColor: Colors.$primario,
        borderWidth: 2,
        marginTop: 10,
    },
    fondo2: {
        position: 'absolute',
        zIndex: 0,
        width: 450,
        height: 750,
        opacity: 0.5,
    }
}
