export default {
    $sizeSmall: '12rem',
    $sizeTitle: '1.9rem',
    $sizeSubtitle: '1.1rem',
    $size22: '1.4rem',
    $size20: '1.24rem',
    $size18: '1.04rem',
    $size16: '0.88rem',
    $size14: '0.777rem',
    $size12: '0.7rem',
    $size10: '0.62rem',
    $size26: '1.625rem',
    $sizeNormal: '1rem',
    $montserratMedium: 'montserratMedium',
    $montserratLight: 'montserratLight',
    $montserratRegular: 'montserratRegular',
    $montserratExtraBold: 'montserratExtraBold',
    $poppinslight: 'Poppins-Light',
    $poppinsregular: 'Poppins-Regular',
    $poppinsmedium: 'PoppinsMedium',
};