import { Env } from "../Utils/enviroments";

const Images: any = {
  //Backgrounds
  fondoMeb: require('../Resources/Backgrounds/fondoMeb.png'),
  //profileBlackFilter:require('../Resources/Backgrounds/filtro_negro2.png'),
  //grayBackground: require('../Resources/Backgrounds/background.png'),
  //grayBackground2: require('../Resources/Backgrounds/background2.png'),
  //grayBackground3: require('../Resources/Backgrounds/background3.png'),
  //grayBackground4: require('../Resources/Backgrounds/background4.png'),
  //membershipBanner: require('../Resources/Backgrounds/banner_membership.png'),
  //backgroundChallenge: require('../Resources/Backgrounds/background_challenge.png'),
  //backgroundProfile: require('../Resources/Backgrounds/background_profile.png'),
  //backClub: require('../Resources/Backgrounds/clubback.png'),
  //backgroundEditProfile: require('../Resources/Backgrounds/Banner_editar_perfil.png'),
  notificationIcon: require('../Resources/Icons/notification.png'),
  gps: require('../Resources/Icons/gps.png'),
  //backProfile: require('../Resources/Backgrounds/back_profile.png'),
  //sportful:require('../Resources/Images/sportful.jpg'),
  bicycleicon: require('../Resources/Images/Login5GBC.png'),
  bicycleiconBlackYellow: require('../Resources/Images/Login5GBC1.png'),
  rideLoginYellow: Env.plantilla === 'ride' ? require('../Resources/Images/Amarillo-fondo-trasparente.png') : require('../Resources/Images/daviviendaLogo.png'),
  rideLoginWhite: require('../Resources/Images/blanco-fondo-trasparente.png'),
  rideLoginBlack: require('../Resources/Images/negro-fondo-trasparente.png'),
  rideimg: Env.plantilla === 'ride' ? require('../Resources/Images/ride.png') : require('../Resources/Images/daviviendaLogo.png'),
  //club:require('../Resources/Images/club.png'),
  //blackFilter:require('../Resources/Backgrounds/filtro_negro.png'),
  //createEventBg:require('../Resources/Backgrounds/fondo_crear_evento.png'),
  //tutorialBg:require('../Resources/Backgrounds/Bicycle_tutorial_fondo.png'),
  logoMeb: require('../Resources/Images/logoMeb.png'),

  fullStar: require('../Resources/Images/star/full_star.png'),
  borderStar: require('../Resources/Images/star/border_star.png'),

  mapa: require('../Resources/Images/mapa.png'),
  checkRed: require('../Resources/Icons/red_check.png'),
  mailRed: require('../Resources/Icons/mail_red.png'),
  passwordRed: require('../Resources/Icons/password_red.png'),
  //logoClub: require('../Resources/Images/logo_club.png'),
  //clubImage: require('../Resources/Images/clubImage.png'),
  //finishing: require('../Resources/Images/finishing1.png'),
  finishing2: require('../Resources/Images/finishing2.png'),
  memberImage: require('../Resources/Images/member.png'),
  //competition: require('../Resources/Images/competition.png'),
  //challenge: require('../Resources/Images/eventDefault.png'),
  //shield:require('../Resources/Images/bicycle2.jpg'),
  bicy: require('../Resources/Images/logoBicy.png'),
  male: require('../Resources/Icons/male.png'),
  female: require('../Resources/Icons/female.png'),
  //ruta corporativa
  //reservaRuta : require('../Resources/Backgrounds/ReservaRutaCorporativa.png'),
  //mapaRuta : require('../Resources/Backgrounds/MapaRuta.png'),
  //qrRuta : require('../Resources/Backgrounds/qrBack.png'),
  //calificar : require('../Resources/Backgrounds/calificarRuta.png'),
  //indicadores : require('../Resources/Backgrounds/indicadoresRuta.png'),
  puntoMap: require('../Resources/Icons/Punto.png'),
  //Icons
  eventOfficialFilter: require('../Resources/Icons/icono_carrera_oficial.png'),
  eventClubFilter: require('../Resources/Icons/icono_carrera_clubes.png'),
  yellowBk: require('../Resources/Icons/icono_ciclista_amarillo.png'),
  whiteBk: require('../Resources/Icons/icono_ciclista_blanco.png'),
  yellowFt: require('../Resources/Icons/icono_runner_amarillo.png'),
  whiteFt: require('../Resources/Icons/icono_runner_blanco.png'),
  redTraffic: require('../Resources/Icons/iconos_encuesta-01.png'),
  redDangerousD: require('../Resources/Icons/iconos_encuesta-02.png'),
  redRoadC: require('../Resources/Icons/iconos_encuesta-03.png'),
  redBikeway: require('../Resources/Icons/iconos_encuesta-04.png'),
  redAccesibility: require('../Resources/Icons/iconos_encuesta-05.png'),
  redFunf: require('../Resources/Icons/iconos_encuesta-06.png'),
  blackCircle: require('../Resources/Icons/circulonegro.png'),
  groupCircle: require('../Resources/Icons/grupo_368.png'),
  adjuntar: require('../Resources/Icons/icono_adjuntar.png'),
  yellowDot: require('../Resources/Icons/circulo_amarillo.png'),
  yellowOk: require('../Resources/Icons/yellow_ok.png'),
  yellowTrophy: require('../Resources/Icons/icono_premio.png'),
  progressBike: require('../Resources/Icons/progress_white.png'),
  redHand: require('../Resources/Icons/hand_red.png'),
  redMedal: require('../Resources/Icons/medal_red.png'),
  whiteMedal: require('../Resources/Icons/medal_white.png'),
  redCamera: require('../Resources/Icons/iconos_camara.png'),
  listRed: require('../Resources/Icons/list_red.png'),
  calendarRed: require('../Resources/Icons/calendar_red.png'),
  newCalendar: require('../Resources/Icons/newCalendar.png'),
  profileRed: require('../Resources/Icons/profile_red.png'),
  filterEvents: require('../Resources/Icons/icono_filtro.png'),
  createEvent: require('../Resources/Icons/icono_crear.png'),
  clubType: require('../Resources/Icons/icono_club.png'),
  clubRedType: require('../Resources/Icons/icono_club2.png'),
  officialType: require('../Resources/Icons/icono_estrella.png'),
  searchRed: require('../Resources/Icons/search_red.png'),
  supportRed: require('../Resources/Icons/support_red.png'),
  iconClub: require('../Resources/Icons/icon_club.png'),
  cameraRed: require('../Resources/Icons/camera_red.png'),
  arrowRightRed: require('../Resources/Icons/right_red.png'),
  bicycleRed: require('../Resources/Icons/bicycle_red.png'),
  bellWhite: require('../Resources/Icons/bell_white.png'),
  editRed: require('../Resources/Icons/edit_red.png'),
  diamondRed: require('../Resources/Icons/diamond_red.png'),
  syncRed: require('../Resources/Icons/sync_red.png'),
  settingsRed: require('../Resources/Icons/settings_red.png'),
  goBackRed: require('../Resources/Icons/go_back_red.png'),
  goBackWhite: require('../Resources/Icons/go_back_white.png'),
  goBackYellowNo: require('../Resources/Icons/backyellow.png'),
  iconPickerRed: require('../Resources/Icons/icon_picker_red.png'),
  iconPickerYellow: require('../Resources/Icons/icon_picker_yellow.png'),
  iconPickerGreen: require('../Resources/Icons/icon_picker_green.png'),
  iconPickerWhite: require('../Resources/Icons/icon_picker_white.png'),
  questionRed: require('../Resources/Icons/question_red.png'),
  topIcon: require('../Resources/Icons/topicon.png'),
  closeBlack: require('../Resources/Icons/close_black.png'),
  userIcon: require('../Resources/Icons/user.png'),
  listIcon: require('../Resources/Icons/list.png'),
  calendarIcon: require('../Resources/Icons/calendar.png'),
  handIcon: require('../Resources/Icons/hand.png'),
  infoIcon: require('../Resources/Icons/nube.png'),
  whiteCheck: require('../Resources/Icons/chulo.png'),
  grayPadlock: require('../Resources/Icons/padlock_gray.png'),
  googleLogo: require('../Resources/Icons/logo_google.png'),
  facebookLogo: require('../Resources/Icons/logo_facebook.png'),
  yellowPassword: require('../Resources/Icons/icono_password_yellow.png'),
  yellowMail: require('../Resources/Icons/icono_mail_yellow.png'),
  grayMail: require('../Resources/Icons/gray_mail.png'),
  redDiamond: require('../Resources/Icons/diamond_red.png'),
  redCheckFill: require('../Resources/Icons/check_red_fill.png'),
  redCheck: require('../Resources/Icons/check_red.png'),
  redCard: require('../Resources/Icons/card_red.png'),
  yellowBike: require('../Resources/Icons/trazado31.png'),
  whiteFoot: require('../Resources/Icons/grupo9.png'),
  whiteCircle: require('../Resources/Icons/elipse24.png'),
  yellowCircle: require('../Resources/Icons/elipse23.png'),
  close: require('../Resources/Icons/close.png'),
  arrow_back: require('../Resources/Icons/arrow_back.png'),
  arrow_white_back: require('../Resources/Icons/backwhite.png'),
  hand_good: require('../Resources/Icons/hand_good.png'),
  cars: require('../Resources/Icons/cars.png'),
  triangle: require('../Resources/Icons/triangle.png'),
  state: require('../Resources/Icons/state.png'),
  bicycle_table: require('../Resources/Icons/Bicycle_table.png'),
  accessibility: require('../Resources/Icons/accessibility.png'),
  fun: require('../Resources/Icons/fun.png'),
  trophy: require('../Resources/Icons/trophy.png'),
  creditCard: require('../Resources/Icons/icon_credit_car2.png'),
  shoeIcon: require('../Resources/Icons/Shoe.png'),
  quiz01: require('../Resources/Icons/iconos_encuesta-01.png'),
  quiz02: require('../Resources/Icons/iconos_encuesta-02.png'),
  quiz03: require('../Resources/Icons/iconos_encuesta-03.png'),
  quiz04: require('../Resources/Icons/iconos_encuesta-04.png'),
  quiz05: require('../Resources/Icons/iconos_encuesta-05.png'),
  quiz06: require('../Resources/Icons/iconos_encuesta-06.png'),
  goBackYellow: require('../Resources/Icons/icono_flecha-amarilla.png'),
  grayPersonIcon: require('../Resources/Icons/Icono_foto_gris.png'),
  greenArrows: require('../Resources/Icons/icono_triangulos-horizontal.png'),
  dotsIcon: require('../Resources/Icons/icono_puntos.png'),
  arrowGreenForward: require('../Resources/Icons/arrow_circle_forward.png'),
  settingsIcon: require('../Resources/Icons/Icono_configuracion.png'),
  faqIcon: require('../Resources/Icons/Icono_pregunta.png'),
  supportIcon: require('../Resources/Icons/Icono_soporte.png'),
  MenuIcon: require('../Resources/Icons/Menu.png'),
  iconOk: require('../Resources/Icons/ok.png'),
  iconBad: require('../Resources/Icons/bad.png'),
  iconBike: require('../Resources/Icons/iconBike.png'),
  lockBike1: require('../Resources/Icons/lockBike1.png'),
  lockBike2: require('../Resources/Icons/lockBike2.png'),
  vectorDaviviendaRojo: require('../Resources/Icons/Davivienda-rojo.png'),
  vectorDaviviendaNegro: require('../Resources/Icons/Davivienda-Negro.png'),
  vectorDaviviendaBlanco: require('../Resources/Icons/Davivienda-blanco.png'),
  scanVector: require('../Resources/Icons/scaner-este-codigo.png'),
  camera: require('../Resources/Images/camara.png'),
  //Images
  //tutorial1: require('../Resources/Images/Track_it_up_tutorial_competidor_1.png'),
  //tutorial2: require('../Resources/Images/Track_it_up_tutorial_competidor_2.png'),
  //tutorial3: require('../Resources/Images/Track_it_up_tutorial_competidor_3.png'),
  //tutorial4: require('../Resources/Images/Track_it_up_tutorial_competidor_4_v2.png'),
  defaultSamllBox: require('../Resources/Images/foto_defaultbox.png'),
  logo: require('../Resources/Images/logo.png'),
  //eventsMenu: require('../Resources/Images/Cuadro_clubes_carreras_oficiales.png'),
  //Ranking
  speed: require('../Resources/Icons/iconos_indicadores-01.png'),
  distance: require('../Resources/Icons/iconos_indicadores-02.png'),
  altitude: require('../Resources/Icons/iconos_indicadores-03.png'),
  inclination: require('../Resources/Icons/iconos_indicadores-04.png'),
  cadence: require('../Resources/Icons/iconos_indicadores-05.png'),
  time: require('../Resources/Icons/iconos_indicadores-06.png'),
  maxAceleration: require('../Resources/Icons/iconos_indicadores-07.png'),
  heartRate: require('../Resources/Icons/iconos_indicadores-08.png'),
  calories: require('../Resources/Icons/calories.png'),
  home: require('../Resources/Icons/home.png'),
  power: require('../Resources/Icons/iconos_indicadores-10.png'),
  paginaWeb: require('../Resources/Icons/PaginaWeb.png'),
  email: require('../Resources/Icons/Email.png'),
  telefonoContacto: require('../Resources/Icons/TelefonoContacto.png'),
  co2: require('../Resources/Icons/co2.png'),

  //registroextendido
  //generoM: require('../Resources/Images/botonF.png'),
  //generoH: require('../Resources/Images/botonH.png'),
  //generoMgris: require('../Resources/Images/botonFgris.png'),
  //generoHgris: require('../Resources/Images/botonHgris.png'),
  iconoMapa: require('../Resources/Images/iconomapa.png'),
  //img6: require('../Resources/Images/img6.png'),
  vista10: require('../Resources/Images/vista10.png'),
  //imgSostenible: require('../Resources/Images/imgSostenible.png'),
  //banner1: require('../Resources/Images/banner1.png'),
  //vehiculoCompartido: require('../Resources/Images/btnVehiculoCompartido.png'),
  //vehiculoCompartidoNO: require('../Resources/Images/btnVehiculoCompartidoNO.png'),
  //vehiculoPropio: require('../Resources/Images/btnVehiculoPropio.png'),
  //vehiculoPropioNO: require('../Resources/Images/btnVehiculoPropioNO.png'),
  //vehiculoCarroPool: require('../Resources/Images/btnVehiculoCarroPool.png'),
  //vehiculoCarroPoolNO: require('../Resources/Images/btnVehiculoCarroPoolNO.png'),
  //estacionamientoCompartido: require('../Resources/Images/btnEstacionamientoCompartido.png'),
  //estacionamientoCompartidoNO: require('../Resources/Images/btnEstacionamientoCompartidoNO.png'),
  //rutaCorporativa: require('../Resources/Images/btnRutaCorporativa.png'),
  //rutaCorporativaNO: require('../Resources/Images/btnRutaCorporativaNO.png'),
  //aplicacionDavivienda : require ('../Resources/Backgrounds/APLICACIONES-LOGO-DAVIVIENDA.png'),
  //daviviendaImage : require('../Resources/Backgrounds/davivienda.png'),
  //bcImage : require('../Resources/Backgrounds/bicyclecapital.png'),
  //bandera:require('../Resources/Images/bandera.jpg'),
  //vehicleprivate
  daviviendaLogo: require('../Resources/Images/daviviendaLogo.png'),
  daviviendacolor: require('../Resources/Images/daviviendacolor.png'),
  vehicleP_carro: require('../Resources/Images/vehicleP_carro.png'),
  vehicleP_moto: require('../Resources/Images/vehicleP_moto.png'),
  vehicleP_ebike: require('../Resources/Images/vehicleP_ebike.png'),
  vehicleP_bici: require('../Resources/Images/vehicleP_bici.png'),
  vehicleP_patineta: require('../Resources/Images/vehicleP_patineta.png'),
  vpCarro: require('../Resources/vehiculoparticular/carro.png'),
  vpbike: require('../Resources/vehiculoparticular/bicicleta.png'),
  vpbici: require('../Resources/vehiculoparticular/bici.png'),
  vpScooter: require('../Resources/vehiculoparticular/scooter.png'),
  vpMoto: require('../Resources/vehiculoparticular/moto.png'),
  vpHelicoptero: require('../Resources/vehiculoparticular/helicoptero.png'),
  vpEMoto: require('../Resources/vehiculoparticular/e-moto.png'),
  vpECar: require('../Resources/vehiculoparticular/e-car.png'),
  vpClima: require('../Resources/vehiculoparticular/clima.png'),
  vpEbike: require('../Resources/vehiculoparticular/ebike.png'),
  vpmas: require('../Resources/Images/vpmas.png'),
  resumen: require('../Resources/Images/resumen.png'),
  historico: require('../Resources/Images/historico.png'),
  vpkm: require('../Resources/Images/vpkm.png'),
  vpmin: require('../Resources/Images/vpmin.png'),
  vppts: require('../Resources/Images/vppts.png'),
  vpsoporte: require('../Resources/Images/vpsoporte.png'),
  reloj: require('../Resources/Icons/reloj.png'),
  vpreloj: require('../Resources/Images/vpreloj.png'),
  fondo2: require('../Resources/Images/fondo2.png'),
  vptest: require('../Resources/Images/vptest.png'),
  vpcal1: require('../Resources/Images/vpcal1.png'),
  vpcal2: require('../Resources/Images/vpcal2.png'),
  //vp_img_principal:require('../Resources/Images/vp_img_principal.png'),
  daviviendaColor: require('../Resources/Icons/daviviendafullcolor.png'),
  transpublico: require('../Resources/vehiculoparticular/transportePublico.png'),
  vpBicicleta: require('../Resources/vehiculoparticular/bicicleta.png'),
  vpAvion: require('../Resources/vehiculoparticular/avion.png'),
  vpBus: require('../Resources/vehiculoparticular/bus.png'),
  vpMetro: require('../Resources/vehiculoparticular/metro.png'),
  vpPeaton: require('../Resources/vehiculoparticular/peaton.png'),
  vpTaxi: require('../Resources/vehiculoparticular/taxi.png'),
  vpTren: require('../Resources/vehiculoparticular/tren.png'),
  vpCalorias: require('../Resources/vehiculoparticular/calorias.png'),
  vpCo2: require('../Resources/vehiculoparticular/co2.png'),
  vpDistancia: require('../Resources/vehiculoparticular/distancia.png'),
  vpTiempo: require('../Resources/vehiculoparticular/tiempo.png'),
  vpFecha: require('../Resources/vehiculoparticular/fecha.png'),
  vpini: require('../Resources/vehiculoparticular/ubiSalida.png'),
  vpllegada: require('../Resources/vehiculoparticular/ubiLlegada.png'),
  vpviajefinalizado: require('../Resources/vehiculoparticular/viajefinalizado.png'),
  vpcamara: require('../Resources/vehiculoparticular/camara.png'),
  vpgaleria: require('../Resources/vehiculoparticular/galeria.png'),
  vpaddimg: require('../Resources/vehiculoparticular/addimagen.png'),
  trofeo: require('../Resources/vehiculoparticular/trofeo.png'),
  //Parqueadero
  park1: require('../Resources/Images/park1.png'),
  park2: require('../Resources/Images/park2.png'),
  park3: require('../Resources/Images/park3.png'),
  parqueo_camara: require('../Resources/parqueaderos/camara.png'),
  parqueo_cerrar: require('../Resources/parqueaderos/close-circle.png'),
  ProgresoImagen: require('../Resources/parqueaderos/Progreso-Imagen.png'),
  iconWhatsapp: require('../Resources/parqueaderos/whatsapp.png'),
  iconWhatsapp01: require('../Resources/parqueaderos/whatsapp01.png'),
  MapaImagen: require('../Resources/parqueaderos/Mapa-Imagen.png'),
  IconoAtrasParqueo: require('../Resources/parqueaderos/Iconoatras.png'),
  ImagenScoterParqueo: require('../Resources/parqueaderos/Scooter-Imagen.png'),
  //flechaAtras : require('../Resources/Icons/manBack.png'),
  flechaAtras: Env.plantilla === 'ride' ? require('../Resources/Icons/manBack.png') : require('../Resources/Icons/arrowBackRed.png'),
  flechaAtras3: Env.plantilla === 'ride' ? require('../Resources/Icons/manBack2.png') : require('../Resources/Icons/arrowBackRed2.png'),
  flechaAlFrente: require('../Resources/Icons/manRight.png'),
  scanerImg: require('../Resources/Images/scanerImg.jpg'),
  indicadoresCarpooling: require('../Resources/Images/IndicadoresCarpooling.png'),
  viajeActivo: require('../Resources/Images/viajeActivo.jpeg'),
  rutaGenerada: require('../Resources/Images/generateRute.jpeg'),
  //registro
  regondas: require('../Resources/Images/regondas.png'),
  profilePhoto: require('../Resources/Images/perfilPhoto.jpg'),
  //reserva3g
  ondaWhite: require('../Resources/Images/ondaWhite.png'),
  ondaRed: require('../Resources/Images/ondaRed.png'),
  reserva01: require('../Resources/Images/reserva01.png'),
  bicycle_Icon: require('../Resources/Images/bicycle_Icon.png'),
  patin_Icon: require('../Resources/Images/patin_icon.png'),
  avion_Icon: require('../Resources/Images/icon_avion.png'),
  taxi_Icon: require('../Resources/Images/icon_taxi.png'),
  mapa_Icon: require('../Resources/Images/icon_mapa.png'),
  refresh_Icon: require('../Resources/Images/icon_refresh.png'),
  plus_Icon: require('../Resources/Images/icon_plus.png'),
  bus_Icon: require('../Resources/Images/icon_bus.png'),
  edit_Icon: require('../Resources/Images/icon_edit.png'),
  can_Icon: require('../Resources/Images/icon_can.png'),
  cam_Icon: require('../Resources/Images/icon_cam.png'),
  seting_Icon: require('../Resources/Images/icon_seting.png'),
  puntos_Icon: require('../Resources/Images/icon_puntos.png'),
  //imgchat_car : require('../Resources/Images/imgChatttt.png'),
  bicicleta_Icon: require('../Resources/Images/icon_bicicleta.png'),
  clock_Icon: require('../Resources/Images/icon_clock.png'),
  km_Icon: require('../Resources/Images/icon_km.png'),
  co2_Icon: require('../Resources/Images/icon_co2.png'),
  peaton_Icon: require('../Resources/Images/icon_peaton.png'),
  metro_Icon: require('../Resources/Images/icon_metro.png'),
  tren_Icon: require('../Resources/Images/icon_tren.png'),
  misvehiculos_Icon: require('../Resources/Images/icon_misvehiculos.png'),
  nublado_Icon: require('../Resources/Images/icon_nublado.png'),
  atras_Icon: require('../Resources/Images/icon_atras.png'),
  cycle_Icon: require('../Resources/Images/cycle_icon.png'),
  cycle_key: require('../Resources/Images/key.png'),
  //fondoModal : require('../Resources/Images/fondoModal.png'),
  //fondoModalYellow : require('../Resources/Images/fondoModalYellow.png'),
  //ren_Img : require('../Resources/Images/ren_Img.jpg'),
  //ren_parqueoBici : require('../Resources/Images/ren_parqueoBici.jpg'),
  //fondoReserva : require('../Resources/Images/fondoReserva.png'),
  //fondoRenta : require('../Resources/Images/fondoRenta.png'),
  //fondoVP : require('../Resources/Images/fondoVP.png'),
  //bc
  arrowNextBC: require('../Resources/Icons/arrowNextBC.png'),
  arrowBackBC: require('../Resources/Icons/arrowBackBC.png'),
  //Ride
  Ride1: require('../Resources/Images/ride1.jpg'),
  Ride2: require('../Resources/Images/ride2.jpg'),

  Ride4: require('../Resources/Images/ride4.jpg'),
  Ride4_5: require('../Resources/Images/ride4-5.jpg'),
  Ride5: require('../Resources/Images/ride5.jpg'),
  Ride5_6: require('../Resources/Images/ride5-6.jpg'),
  Ride6: require('../Resources/Images/ride6.jpg'),
  Ride7: require('../Resources/Images/ride7.jpg'),
  Ride8: require('../Resources/Images/ride8.jpg'),
  Ride9: require('../Resources/Images/ride9.jpg'),
  Ride10: require('../Resources/Images/ride10.jpg'),
  Ride10_11: require('../Resources/Images/ride10-11.jpg'),
  Ride11: require('../Resources/Images/ride11.jpg'),
  Ride12: require('../Resources/Images/ride12.jpg'),
  Ride13: require('../Resources/Images/ride13.jpg'),
  Ride14: require('../Resources/Images/ride14.jpg'),
  Ride15: require('../Resources/Images/ride15.jpg'),
  Ride16: require('../Resources/Images/ride16.jpg'),
  Ride17: require('../Resources/Images/ride17.jpg'),
  Ride18: require('../Resources/Images/ride18.jpg'),
  //gema : require('../Resources/Images/gema.png'),
  fondoMapa: require('../Resources/carpooling/fondoMapa.png'),

  //rojotu
  homedavi: require('../Resources/Images/homedavi.png'),
  vectorRojoTu: require('../Resources/Icons/rojotu.png'),
  vectorRojoTu_blanco: require('../Resources/Icons/rojotublanco.png'),
  vectorRojoTu_scaner: require('../Resources/Icons/rojotuscaner.png'),
  mapaResumen: require('../Resources/Images/mapaResumen.png'),
  logoHome: Env.plantilla === 'ride' ? require('../Resources/Images/ride.png') : require('../Resources/Images/daviviendaLogo.png'),
  iconRide: require('../Resources/Icons/iconRide.png'),
  //carpooling
  logoDavi: require('../Resources/gif/logoDavi.gif'),
  menu_icon: require('../Resources/carpooling/iconomenu.png'),
  x_icon: require('../Resources/carpooling/iconox.png'),
  flecha_icon: require('../Resources/carpooling/iconoFlecha.png'),
  e_icon: require('../Resources/carpooling/iconoeditar.png'),
  d_icon: require('../Resources/carpooling/iconoeliminar.png'),
  v_icon: require('../Resources/carpooling/iconovermas.png'),
  n_icon: require('../Resources/carpooling/icononotificacion.png'),
  carroblanco: require('../Resources/carpooling/carroblanco.png'),
  carrorojo: require('../Resources/carpooling/carrorojo.png'),
  carrorojo2: require('../Resources/carpooling/carrorojo2.png'),
  moto: require('../Resources/carpooling/moto.png'),
  iconobillete: require('../Resources/carpooling/iconobillete.png'),
  logodaviplata: require('../Resources/carpooling/logodaviplata.png'),
  iconochatActivo: require('../Resources/carpooling/iconochatActivo.png'),
  iconoalerta: require('../Resources/carpooling/iconoalerta.png'),
  logonequi: require('../Resources/carpooling/logonequi.png'),
  logootro: require('../Resources/carpooling/iconotarjeta.png'),
  iconoatras: require('../Resources/carpooling/iconoatras.png'),
  iconoviajes: require('../Resources/Perfil/icono_viajes.png'),
  iconoSoporte: require('../Resources/Perfil/icono_soporte.png'),
  iconoConfiguracion: require('../Resources/Perfil/icono_configuracion.png'),
  diamante: require('../Resources/Perfil/icono_recompensas.png'),
  estrella: require('../Resources/Perfil/icono_estrella.png'),
  solicitud: require('../Resources/Perfil/icono_solicitud.png'),
  carro: require('../Resources/Perfil/icono_carro.png'),
  like: require('../Resources/Perfil/icono_like.png'),
  userCar: require('../Resources/carpooling/userCar.jpg'),
  iconoviaje: require('../Resources/carpooling/iconoviaje.png'),
  logoDaviRide: Env.plantilla === 'davivienda' ? require('../Resources/Images/logoDaviRide.png') : require('../Resources/Images/logoRide.png'),
  logoTrip: Env.plantilla === 'davivienda' ? require('../Resources/Images/logoDaviRide.png') : require('../Resources/Images/logotrip.png'),
  //movilidad4G
  bluetoothError: require('../Resources/movilidad4g/bluetoothError.png'),
  bluetoothOK: require('../Resources/movilidad4g/bluetoothOK.png'),
  bluetoothRefresh: require('../Resources/movilidad4g/bluetoothRefresh.png'),
  //NewLogin
  userLogin: require('../Resources/Icons/user_login.png'),
  passHidden: require('../Resources/Icons/pass_hidden.png'),
  showPass: require('../Resources/Icons/show_pass.png'),
  lockLogin: require('../Resources/Icons/lock_login.png'),

  linterna_: require('../Resources/imagenes/linterna.png'),
  qr_: require('../Resources/imagenes/qr.png'),
  distancia_: require('../Resources/imagenes/distancia.png'),
  clima_: require('../Resources/imagenes/clima.png'),

  //Drawer
  unirmeDrawer: require('../Resources/carpooling/unirmeDrawer.png'),
  compartirDrawer: require('../Resources/carpooling/compartirDrawer.png'),
  itinerarioDrawer: require('../Resources/carpooling/itinerarioDrawer.png'),
  historialDrawer: require('../Resources/carpooling/historialDrawer.png'),
  soporteDrawer: require('../Resources/carpooling/soporteDrawer.png'),
  fondo_tarjeta: require('../Resources/Perfil/fondo_tarjeta.png'),
  catalogo_img: require('../Resources/Perfil/catalogo.jpg'),
  robot_bike: require('../Resources/Icons/robot_bike_meb.png'),
};



export default Images;
