import Fonts from '../../../Themes/Fonts';
import Colors from '../../../Themes/Colors';
import {Dimensions} from 'react-native';
import {
  horizontalScale,
  moderateScale,
  verticalScale,
} from '../../../Themes/Metrics';

export default {
  generales: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'blue',
  },
  contentTop2: {
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height,
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'space-around',
    position: 'relative',
    zIndex: 10,
  },
  titleSelect2: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    fontSize: 20,
    fontFamily: Fonts.$poppinsregular,
    color: Colors.$texto,
  },
  safeArea: {
    flex: 1,
    width: '100%',
    backgroundColor: Colors.$blanco,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cajaImgVP: {
    position: 'absolute',
    width: 200,
    height: 200,
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 100
  },
  imgVP: {
    width: 220,
    height: 220,
},
  fondoReserva: {
    borderRadius: 130,
    width: 260,
    height: 260,
    zIndex: 0,
    top: 0
  },
  titleSelect3: {
    width: '80%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    fontSize: moderateScale(16),
    fontFamily: Fonts.$montserratExtraBold,
    backgroundColor: Colors.$blanco,
    color: Colors.$texto,
    marginTop: 20,
    marginBottom: 20,
    padding: 10,
    borderRadius: 5,
  },
  contenedor: {
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height,
    flexDirection: 'column',
    position: 'relative',
    zIndex: 1,
    backgroundColor: 'white'
  },
  contenedorReservaVencio: {
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height,
    backgroundColor: Colors.$tercer,
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnBlack: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: moderateScale(180),
    height: 'auto',
    borderRadius: 25,
  },
  contentTop: {
    width: Dimensions.get('window').width,
    height: 200,
    backgroundColor: Colors.$blanco,
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 70,
  },
  ondaWhite: {
    width: Dimensions.get('window').width,
    height: 70,
    position: 'absolute',
    bottom: 0,
  },
  imgReserva01: {
    width: 300,
    height: 300,
  },
  contenedor2: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: '#fff',
    width: '100%',
    height: '100%',
    alignItems: 'center',
  },
  cajas: {
    flex: 1,
    width: '100%',
    flexDirection: 'column',
    alignItems: 'center',
    marginBottom: 50,
  },
  title: {
    fontFamily: Fonts.$montserratExtraBold,
    fontSize: moderateScale(30),
    textAlign: 'center',
    color: Colors.$texto,
    marginBottom: 5,
  },
  contentTitle: {
    flex: 1,
    width: '100%',
  },
  btnBack: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: Dimensions.get('window').width,
    height: 55,
    position: 'absolute',
    left: 0,
    top: 0,
    zIndex: 10,
    backgroundColor: Colors.$primario,
  },
  imgback: {
    width: Dimensions.get('window').width,
    height: 50,
  },
  titleSelect: {
    width: Dimensions.get('window').width,
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    fontSize: 24,
    fontFamily: Fonts.$poppinsregular,
    color: Colors.$texto,
    marginTop: 20,
    marginBottom: 20,
  },
  itemSelect: {
    backgroundColor: Colors.$primario,
  },
  btnSave: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.$primario,
    width: 150,
    borderRadius: 25,
  },
  btnSaveRentar: {
    backgroundColor: Colors.$primario,
    width: moderateScale(150),
    borderRadius: 25,
    paddingTop: 10,
    paddingBottom: 10,
  },
  btnCenter: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
  },
  btnSelect__: {
    width: Dimensions.get('window').width,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.$blanco,
    padding: 5,
  },
  btn_q: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 30,
    borderRadius: 25,
  },
  btnCenter3: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  cajaHorizontal: {
    width: Dimensions.get('window').width*.4,
    flexDirection: 'row',
    flexWrap: 'nowrap',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  cajaBtnReservar: {
    backgroundColor: Colors.$blanco,
    padding: 2,
  },
  titleSelect4: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    fontSize: 20,
    fontFamily: Fonts.$poppinsregular,
    color: Colors.$texto,
    marginTop: 5,
    marginBottom: 20,
  },
  btnRed: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.$primario,
    width: 180,
    height: 'auto',
    borderRadius: 25,
    paddingTop: 10,
    paddingBottom: 10,
  },
  btnTextColorWhite: {
    color: Colors.$blanco,
    fontSize: moderateScale(20),
  },
  btnSaveColor: {
    color: Colors.$blanco,
    fontSize: 20,
    textAlign: 'center',
    fontFamily: Fonts.$poppinsregular
  },
  btnSaveColor3: {
    color: Colors.$texto,
    fontSize: moderateScale(20),
    textAlign: 'center',
  },
  cajaImgReserva: {
    width: Dimensions.get('window').width,
    height: 350,
    alignItems: 'center',
    justifyContent: 'center',
  },
  imgReserva: {
    width: moderateScale(210),
    height: moderateScale(210),
    borderRadius: moderateScale(10),
  },
  cajaImgGuaya: {
    width: moderateScale(210),
    height: moderateScale(210),
    alignSelf: 'center',
    justifyContent: 'center',
  },
  imgGuaya: {
    width: '100%',
    height: '100%',
  },
  msnHorarios: {
    width: 370,
    height: 'auto',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: moderateScale(50),
    fontFamily: Fonts.$size26,
    textAlign: 'center',
  },
  denegado: {
    fontFamily: Fonts.$size26,
    fontSize: moderateScale(16),
    backgroundColor: Colors.$tercer,
    color: Colors.$texto,
    width: '80%',
    marginBottom: 5,
    padding: 10,
    borderRadius: 5,
  },
  denegado2: {
    fontFamily: Fonts.$size26,
    fontSize: moderateScale(20),
    textAlign: 'center',
    color: Colors.$texto,
    width: Dimensions.get('window').width,
    paddingLeft: 10,
    borderRadius: 5,
  },
  denegado3: {
    fontFamily: Fonts.$size26,
    fontSize: moderateScale(24),
    textAlign: 'center',
    color: Colors.$texto,
    width: Dimensions.get('window').width*.7,
    paddingLeft: 10,
    borderRadius: 5,
    marginTop: 100
  },
  denegado4: {
    fontFamily: Fonts.$size26,
    fontSize: moderateScale(30),
    textAlign: 'center',
    color: Colors.$texto,
    width: Dimensions.get('window').width*.7,
    paddingLeft: 10,
    borderRadius: 5,
    marginTop: 10,
    marginBottom: 10
  },
  textCargando: {
    fontFamily: Fonts.$size24,
    fontSize: moderateScale(20),
    textAlign: 'center',
    color: Colors.$texto,
    width: Dimensions.get('window').width*.7,
    paddingLeft: 10,
    borderRadius: 5,
    marginTop: 50,
    marginBottom: 10
  },
  aceptado: {
    fontFamily: Fonts.$size26,
    fontSize: moderateScale(28),
    color: Colors.$primario,
    marginBottom: 8,
    width: Dimensions.get('window').width * 0.8,
    paddingLeft: 10,
    borderRadius: 5,
    textAlign: 'center',
  },
  aceptado3: {
    width: Dimensions.get('window').width * 0.8,
    fontFamily: Fonts.$size26,
    fontSize: moderateScale(22),
    marginTop: 200,
    textAlign: 'center',
  },
  textVehiculo: {
    fontSize: moderateScale(20),
    color: Colors.$texto,
    marginTop: 5,
    marginBottom: 5
  },
  textVehiculo2: {
    fontSize: moderateScale(16),
    color: Colors.$texto,
  },
  btnVehiculos: {
    width: 95,
    height: 95,
    backgroundColor: Colors.$tercer,
    margin: moderateScale(5),
    alignSelf: 'center',
    justifyContent: 'center',
    borderRadius: 18,
  },
  btnVehiculosSelect: {
    width: 95,
    height: 95,
    backgroundColor: Colors.$adicional,    
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 18,
    padding: 10,
  },
  cajaTextVehiuclos: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconBici: {
    width: 40,
    height: 40,
  },
  cajaCuentaRegresiva: {
    height: verticalScale(150),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: verticalScale(20),
    marginBottom: verticalScale(20),
  },
  subcajaCuentaRegresiva: {
    width: 70,
    flexDirection: 'column',
    alignItems: 'center',
    backgroundColor: Colors.$primario,
    margin: 5,
    padding: 5,
    borderRadius: 10,    
  },
  numeroCuentaRegrasiva: {
    fontSize: 20,
    color: Colors.$blanco,
    fontFamily: Fonts.$poppinsregular,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    margin: moderateScale(15),
  },
  subtextoCuentaR: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 10,
    textAlign: 'center',
    fontFamily: Fonts.$poppinsregular,
    color: Colors.$blanco,
  },

  input: {
    width: '100%',
    height: 'auto',
    borderBottomWidth: 1,
    borderColor: '#CCCCCC',
    fontSize: moderateScale(40),
    fontFamily: Fonts.$montserratExtraBold,
    textAlign: 'center',
  },
  contentCenter: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnSaveOK: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.$primario,
    width: 350,
    height: 'auto',
    borderRadius: 25,
    padding: 10,
  },
  colorText: {
    color: Colors.$blanco,
    width: Dimensions.get("window").width,
    padding: 20,
    fontSize: 20,
    textAlign: "center"
  },
  btnSaveOKdevolver: {
    backgroundColor: Colors.$primario,
    width: moderateScale(150),
    borderRadius: 25,
    paddingTop: 10,
    paddingBottom: 10,
  },
  btnSI: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.$primario,
    width: 60,
    height: 60,
    borderRadius: 30,
  },
  btnAntes: {
    width: 60,
    height: 60,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.$texto,
  },
  btnCancelar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.$red,
    width: moderateScale(150),
    borderRadius: 25,
    paddingTop: 10,
    paddingBottom: 10,
  },
  btnSaveColor2: {
    color: Colors.$texto,
    fontSize: moderateScale(20),
  },
  btnSaveColor2White: {
    fontSize: 18,
    fontFamily: Fonts.$poppinsregular,
    color: Colors.$blanco,
    textAlign: 'center',
  },
  aceptado2: {
    fontFamily: Fonts.$poppinsmedium,
    fontSize: 24,
    color: Colors.$texto,
    marginBottom: 8,
    width: "100%",
    paddingLeft: 10,
    borderRadius: 10,
    padding: 5,
    textAlign: 'center',
  },
  contentMsn: {
    width: Dimensions.get("window").width,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.$blanco,
    paddingTop: 20,
    paddingBottom: 20
  },
  contentMsn2: {
    width: Dimensions.get("window").width,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.$blanco,
    paddingTop: 20,
    paddingBottom: 20
  },
  fichaReserva: {
    width: Dimensions.get("window").width*.9,
    justifyContent: 'center',
    marginTop: 10,
    padding: 30,
    backgroundColor: Colors.$blanco,
  },
  cajaCod: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'space-around',
    backgroundColor: Colors.$tercer,
    paddingBottom: 20,
    paddingTop: 20
  },
  cajaCod2: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'space-around',
    width: Dimensions.get("window").width,
    backgroundColor: Colors.$blanco,
    paddingBottom: 20,
    marginTop: -50,
    borderRadius: 30,
    shadowColor: "#000",
    shadowOffset: {
      width: 5,
      height: 5,
    },
    shadowOpacity: 1,
    shadowRadius: 5,
    elevation: 8,
  },
  cajaDatosViaje: {
    width: Dimensions.get("window").width,
    height: Dimensions.get("window").height*.85, 
    backgroundColor: Colors.$blanco,
    flex: 1,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  cajaViajePrograso: {
    backgroundColor: Colors.$texto,
  },
  textTituloClave: {
    color: 'black',
    fontSize: moderateScale(18),
    marginBottom : verticalScale(20)
  },
  textTituloClave2: {
    fontFamily: Fonts.$poppinsmedium,
    fontSize: 24,
    color: Colors.$texto50,
    position: 'absolute',
    top: 50,

  },
  textTituloClave3: {
    color: Colors.$texto,
    fontSize: 18,
    fontFamily: Fonts.$poppinsregular
  },
  textTituloClave4: {
    color: Colors.$texto,
    fontSize: 20,
    fontFamily: Fonts.$poppinsmedium,
    justifyContent: 'center',
    alignItems: 'center', 
    textAlign: 'center'
  },
  textTituloClave5: {
    textAlign: 'center',
    color: Colors.$texto50,
    fontSize: 18,
    fontFamily: Fonts.$poppinsregular
  },
  
  textClave: {
    fontSize: 24,
    color: Colors.$texto,
    textAlign: 'center',
    fontFamily: Fonts.$poppinsmedium
  },
  boxPrincipalItemsReserva: {
    flex: 1,
    width: Dimensions.get('window').width,
    minHeight: Dimensions.get('window').height*.6,
    backgroundColor: Colors.$blanco,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingTop: 30,
    
  },
  boxPrincipalItems: {
    flex: 1,
    width: Dimensions.get('window').width,
    minHeight: Dimensions.get('window').height*.6,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    backgroundColor: Colors.$blanco,
    paddingTop: 30,
    paddingLeft: 15
  },
  boxPrincipalItems2: {
    width: Dimensions.get('window').width,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  boxPrincipalItems3: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  boxPrincipalItems4: {
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height * 0.9,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  cajaBtnRentar: {
    width: "100%",
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingBottom: 20,
    backgroundColor: 'violet'
  },
  cajaSiNo: {
    width: Dimensions.get('window').width*.4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    marginBottom: 10,
    
  },
  map: {
    flex: 1,
    width: '100%',
    height: 400,
  },
  textoInput: {
    width: '100%',
    backgroundColor: '#cecece',
  },
  cajaFalla: {
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 20,
  },
  caja_select:{
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 20,
    backgroundColor: '#f60',
  },
  vpsoporte: {
    width: 60,
    height: 60,
  },
  stationStyle: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    width: Dimensions.get('window').width,
    height: 'auto', 
    backgroundColor: Colors.$blanco,
    zIndex: 10
  },

  btnCenter1: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 10,
  },
  btnSaveOK2: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.$primario,
    width: 350,
    height: 'auto',
    borderRadius: 25,
    padding: 10,
  },
  btnSaveColor2: {
    color: Colors.$blanco,
    fontSize : 20,
    fontFamily: Fonts.$poppinsregular,
    textAlign: 'center',
},
//cronometro
cajaSubIn: {
  width: Dimensions.get("window").width,
  alignItems: "center",
  justifyContent: "center",
},
subIndicadores: {
  width: 120, 
  height: 120,
  backgroundColor: Colors.$primario,
  margin: 5,
  alignItems: "center",
  justifyContent: 'center',
  borderRadius: 60,
  flexDirection: 'column',
  zIndex: 8,
},
textsubIndicadures:{
  color: Colors.$cuarto,
  fontSize: 18,
  fontFamily: 'bold',
},
cajaMns: {
  marginTop: 100,
  width: Dimensions.get('window').width,
  height: Dimensions.get('window').height, 
  alignItems: 'center',
  justifyContent: 'center',
  flexDirection: 'row',
  flexWrap: 'wrap',
}
};
