import Fonts from '../../../Themes/Fonts';
import Colors from '../../../Themes/Colors';
import { Dimensions } from 'react-native';

export default {
    contenedor:{
        flex: 1,
        width: Dimensions.get("window").width,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: Colors.$blanco,
        position: 'relative',
    },
    cajaMapa: {
        width: Dimensions.get("window").width,
        height: Dimensions.get("window").height*.7,
    },
    cajaFuncionalidad: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        width: Dimensions.get("window").width,
        height: 'auto',
        backgroundColor: Colors.$blanco,
    },
    cajaIndicadoress: {
        width: Dimensions.get('window').width*.8,
        flexDirection: 'row',
        flexWrap: 'wrap',
        alignItems: 'center',
        justifyContent: 'space-around'
    },
    subcajaIndicadoress: {
        width: 150,
        height: 160,
        backgroundColor: Colors.$blanco,
        marginBottom: 20,
        borderRadius: 20,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 3,
        },
        shadowOpacity: 0.5,
        shadowRadius: 4.65,
        elevation: 7,
        borderColor: Colors.$secundario50,
        borderWidth: 2,
        alignItems: 'center',
        justifyContent: 'center',
    },
    subRaya: {
        height: 2, 
        width: 410, 
        backgroundColor: 'transparent', 
        alignSelf: 'center',
    },
    btnFlechaBack: {
        width: 40, 
        margin: 4,
        position: 'absolute',
        left: 0,
        zIndex: 10,
    },
    contentTop: {
        flex: 1,
        backgroundColor: Colors.$primario,
        with: '100%',
        justifyContent: 'center',
        alignItems: 'center',
    },    
    contenedorQR: {
        flex: 1,
        flexDirection: 'column', 
        justifyContent: 'center',
        alignItems: 'center',
        overflow: 'hidden',
        width: 350,
        height: 650,
    },
    cajaQR: {
        width: 350,
        height: 650,
    },
    centerText: {
        flex: 1,
        fontSize: 16,
        zIndex: 10,
    },
    textBold: {
        fontWeight: '300',
        color: '#000'
    },
    buttonText: {
        fontSize: 21,
        color: 'rgb(0,122,255)'
    },
    buttonTouchable: {
        flexDirection: "row",
        alignItems: 'center', 
        justifyContent: 'center', 
        backgroundColor: Colors.$primario,
        width: 180, 
        height: 'auto', 
        borderRadius: 25,
        paddingTop: 10,
        paddingBottom: 10,
    },
    buttonNext: {
        flexDirection: "row",
        alignItems: 'center', 
        justifyContent: 'center', 
        backgroundColor: '#878787',
        width: 180, 
        height: 'auto', 
        borderRadius: 25,
        paddingTop: 10,
        paddingBottom: 10,
    },
    divInput: {
        width: 300,
        backgroundColor: '#fff',
        borderRadius: 0,
        marginBottom: 10,
        marginTop: 20,
        borderWidth: 4,
        borderColor: "red",
    },
    input:{
        width: '100%',
        height: 'auto',
        borderColor: Colors.$primario,
        borderWidth: 4,
        fontSize: 20,
        fontFamily: Fonts.$size26,
        textAlign: 'center',
    },
    //cronometro
    container: {
        flex: 1,
        backgroundColor: '#fff',
        alignItems: 'center', 
        justifyContent: 'center',
    },
    map: {
        flex: 1,
        position: 'absolute',
        width: Dimensions.get("window").width,
        height:  Dimensions.get("window").height,
        top: 0,
    },
    map2: {
        flex: 1,
        width: Dimensions.get("window").width,
        height:  Dimensions.get("window").height,
    },
    cajabotones: {
        width: Dimensions.get("window").width*.8,
        alignItems: 'center',
        justifyContent: 'space-around',
        flexDirection: 'row',
    },
    cajabotones2: {
        width: Dimensions.get("window").width*.8,
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
        backgroundColor: 'green'
    },
    cajainformacion: {
        width: Dimensions.get("window").width,
        height: "100%",
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    cajaIndicadores: {
        flex: 1,
        width: Dimensions.get("window").width,
        height: Dimensions.get("window").height, 
        alignItems: "center", 
        justifyContent: "center", 
        flexDirection: "row",
        flexWrap: "wrap",
        left: 0,
        top: 0,
        zIndex: 100,
    },
    cajaIndicadoresTrip: {
        width: Dimensions.get("window").width, 
        alignItems: "center", 
        justifyContent: "center", 
        flexDirection: "row",
        backgroundColor: "rgba(0,0,0, .8)",
        marginBottom: 10
    },
    cajaSubIn: {
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
    },
    subIndicadores: {
        width: 70, 
        height: 70,
        backgroundColor: Colors.$blanco,
        margin: 5,
        alignItems: "center",
        justifyContent: 'center',
        borderRadius: 60,
        flexDirection: 'column',
        zIndex: 8,
    },
    textsubIndicadures:{
        color: Colors.$texto,
        fontSize: 14,
        fontFamily: 'bold',
    },
    cajaBtnTerminar:{
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
        marginTop: 10,
        marginBottom: 10,
    },
    botonTerminarViaje: {
        backgroundColor: 'white',
        paddingLeft: 20,
        paddingRight: 20,
        borderRadius: 15,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 3,
        },
        shadowOpacity: 0.5,
        shadowRadius: 4.65,
        elevation: 7,
        borderColor: Colors.$primario,
        borderWidth: 2,
    },
    btnTextoTerminarViaje: {
        color: '#878787',
        fontSize: 20,
        fontFamily: 'bold',
    },
    botonPausarViaje: {
        backgroundColor: 'yellow',
        padding: 10,
        borderRadius: 15,
    },
    btnTextoPausarViaje: {
        color: Colors.$texto,
        fontSize: 20,
        fontFamily: 'bold',
        textAlign: 'center',
    },
    botonReanudar: {
        alignItems: 'center',
        height: 50,
        backgroundColor: Colors.$primario,
        padding: 10,
        textAlign: 'center',
        borderRadius: 10,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 10,
        },
        shadowOpacity: 0.5,
        shadowRadius: 4.65,
        elevation: 7,
    },
    botonFinalizar: {
        alignItems: 'center',
        height: 50,
        backgroundColor: Colors.$primario,
        padding: 10,
        textAlign: 'center',
        borderRadius: 15,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 10,
        },
        shadowOpacity: 0.5,
        shadowRadius: 4.65,
        elevation: 7,
        zIndex: 1000
    },
    botonIniciarViaje3: {
        alignItems: 'center',
        width: Dimensions.get("window").width*.6,
        height: 50,
        backgroundColor: Colors.$primario,
        padding: 10,
        textAlign: 'center',
        borderRadius: 15,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 10,
        },
        shadowOpacity: 0.5,
        shadowRadius: 4.65,
        elevation: 7,
    },
    botonIniciarViaje4: {
        alignItems: 'center',
        height: 100,
        width: 100,
        backgroundColor: Colors.$primario,
        padding: 10,
        textAlign: 'center',
        justifyContent: 'center',
        borderRadius: 50,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 10,
        },
        shadowOpacity: 0.5,
        shadowRadius: 4.65,
        elevation: 7,
    },
    botonIniciarViaje5: {
        flex: 1,
        alignItems: 'center',
        width: Dimensions.get("window").width*.6,
        height: 50,
        backgroundColor: Colors.$primario,
        padding: 10,
        textAlign: 'center',
        borderRadius: 15,
        position: 'absolute',
        bottom: 100,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 10,
        },
        shadowOpacity: 0.5,
        shadowRadius: 4.65,
        elevation: 7,
    },
    btnTextoIniciarViaje: {
        color: Colors.$blanco,
        fontSize: 20,
        fontFamily: Fonts.$poppinsregular,
    },
    cajaIndicadoresClima: {
        flexDirection: "column",
        justifyContent: "space-between",
        alignItems: "center",
        zIndex: 100,
        position: "absolute",
        bottom: 30,
        padding: 10,
    },
    cajaclima: {
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#537eaf",
        borderRadius: 10,
        shadowColor: Colors.$texto,
        shadowOffset: {
            width: 0,
            height: 3,
        },
        shadowOpacity: 0.29,
        shadowRadius: 4.65,
        elevation: 7,
    },
    itemClima: {
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        margin: 10,
    },
    letranegra: {
        color: Colors.$texto,
        fontFamily: Fonts.$montserratLight,
        fontSize: 12,
    },
    imgClima: {
        width: 50,
        height: 50,
    },
    textClima: {
        fontSize: 16,
        color: Colors.$blanco,
    },
    textClima2: {
        fontSize: 30,
        color: Colors.$blanco,
    },
    cajalogo: {
        width: "100%",
        flex: 1,
        alignItems: "center",
        textAlign: "center",
        justifyContent: "center",
        marginTop: 20,
        marginBottom: 20,
    },
    cajalogo2: {
        width: "100%",
        height: 200,
        flex: 1,
        alignItems: "center",
        marginTop: 40,
        marginBottom: 40,
        backgroundColor: Colors.$blanco
    },
    logocolor: {
        width: "80%",
        height: "100%",
    },
    resumen: {
        width: 40,
        height: 40,
        marginTop: 40,
    },
    letraResumen: {
        color: Colors.$texto,
        fontFamily: Fonts.$montserratMedium,
        fontSize: 22,
    },
    cajaDatosResumen: {
        width: Dimensions.get('window').width,
        backgroundColor: "rgba(0,0,0, .6)",
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        flexWrap: 'wrap',
    },
    vpkm: {
        width: 40,
        height: 40,
        color: Colors.$texto
    },
    vpkm2: {
        width: 30,
        height: 30,
        color: Colors.$texto,
        zIndex: 1000
    },
    cajaDatosItem: {
        width: 80,
        height: 80,
        backgroundColor: Colors.$blanco,
        borderRadius: 10,
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        margin: 10,
    },
    cajaDatosItemHome: {
        width: 50,
        height: 50,
        backgroundColor: Colors.$blanco,
        borderRadius: 25,
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        position: 'absolute',
        top: 10,
        left: 10,
        margin: 10,
        zIndex: 1000
    },
    letrablanca: {
        color: Colors.$texto,
        fontFamily: Fonts.$montserratLight,
        fontSize: 14,
    },
    cajaSoporte: {
        width: "100%",
        height: 500,
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
    },
    vpsoporte: {
        width: 80,
        height: 80,
    },
    btnSoporte: {
        backgroundColor: Colors.$primario,
        width: 200,
        height: 40,
        justifyContent: 'center',
        alignItems: "center",
        paddingLeft: 20,
        paddingRight: 20,
        borderRadius: 10,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 3,
        },
        shadowOpacity: 0.5,
        shadowRadius: 4.65,
        elevation: 7,
        borderColor: Colors.$primario,
        borderWidth: 2,
        marginTop: 10,
    },
    fondo2: {
        position: 'absolute',
        zIndex: 0,
        width: 450,
        height: 750,
        opacity: 0.5,
    },
    estamosFinalizando: {
        width: Dimensions.get('window').width,
        height: Dimensions.get('window').height,
        backgroundColor: Colors.$primario,
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 1000,
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
    }
}
