export const FETCH_EVENT_CREATE_BEGIN = 'FETCH_EVENT_CREATE_BEGIN';
export const FETCH_EVENT_CREATE_SUCCESS = 'FETCH_EVENT_CREATE_SUCCESS';
export const FETCH_EVENT_CREATE_FAILURE = 'FETCH_EVENT_CREATE_FAILURE';

export const FETCH_EVENTAWARD_CREATE_BEGIN = 'FETCH_EVENTAWARD_CREATE_BEGIN';
export const FETCH_EVENTAWARD_CREATE_SUCCESS = 'FETCH_EVENTAWARD_CREATE_SUCCESS';
export const FETCH_EVENTAWARD_CREATE_FAILURE = 'FETCH_EVENTAWARD_CREATE_FAILURE';

export const FETCH_EVENTUSER_SUBSCRIPTION_BEGIN = 'FETCH_EVENTUSER_SUBSCRIPTION_BEGIN';
export const FETCH_EVENTUSER_SUBSCRIPTION_SUCCESS = 'FETCH_EVENTUSER_SUBSCRIPTION_SUCCESS';
export const FETCH_EVENTUSER_SUBSCRIPTION_FAILURE = 'FETCH_EVENTUSER_SUBSCRIPTION_FAILURE';

export const GET_CHALLENGES = '[challenges] get challenges';
export const SET_CHALLENGES = '[challenges] save challenges';
export const SEARCH_TEXT = '[events] set search text';
export const ACTIVE_SEARCH = '[events] set active search';
export const SET_ACTIVE_TAP = '[events] set active tap';
export const SET_CURRENT_FILTER = '[events] set cuerrent filter';
export const SET_LOADING = '[events] loading';
export const SET_PAGINATION_LIMIT = '[events] pagination limit ';
export const SET_LOAD_IMAGE = '[events] load image';

export const FETCH_UPLOAD_EVENT_IMAGE_BEGIN = 'FETCH_UPLOAD_EVENT_IMAGE_BEGIN';
export const FETCH_UPLOAD_EVENT_IMAGE_SUCCESS = 'FETCH_UPLOAD_EVENT_IMAGE_SUCCESS';
export const FETCH_UPLOAD_EVENT_IMAGE_FAILURE = 'FETCH_UPLOAD_EVENT_IMAGE_FAILURE';

export const FETCH_UPLOAD_EVENTTRACK_IMAGE_BEGIN = 'FETCH_UPLOAD_EVENTTRACK_IMAGE_BEGIN';
export const FETCH_UPLOAD_EVENTTRACK_IMAGE_SUCCESS = 'FETCH_UPLOAD_EVENTTRACK_IMAGE_SUCCESS';
export const FETCH_UPLOAD_EVENTTRACK_IMAGE_FAILURE = 'FETCH_UPLOAD_EVENTTRACK_IMAGE_FAILURE';

export const SELECT_EVENT_BEGIN = 'SELECT_EVENT_BEGIN';
export const SELECT_EVENT_SUCCESS = 'SELECT_EVENT_SUCCESS';
export const SELECT_EVENT_FAILURE = 'SELECT_EVENT_FAILURE';

export const CLEAR_CREATECHALLENGE = 'CLEAR_CREATECHALLENGE';

export const SETTING_AWARD_IMAGE_BEGIN = 'SETTING_AWARD_IMAGE_BEGIN';
export const SETTING_AWARD_IMAGE_SUCCESS = 'SETTING_AWARD_IMAGE_SUCCESS';
export const SETTING_AWARD_IMAGE_FAILURE = 'SETTING_AWARD_IMAGE_FAILURE';

export const FETCH_UPLOAD_TRACKINGS_EVENT_BEGIN = 'FETCH_UPLOAD_TRACKINGS_EVENT_BEGIN';
export const FETCH_UPLOAD_TRACKINGS_EVENT_SUCCESS = 'FETCH_UPLOAD_TRACKINGS_EVENT_SUCCESS';
export const FETCH_UPLOAD_TRACKINGS_EVENT_FAILURE = 'FETCH_UPLOAD_TRACKINGS_EVENT_FAILURE';
