export const FETCH_DEVICE_CONFIGURATION_BEGIN = 'FETCH_DEVICE_CONFIGURATION_BEGIN';
export const FETCH_DEVICE_CONFIGURATION_SUCCESS = 'FETCH_DEVICE_CONFIGURATION_SUCCESS';
export const FETCH_DEVICE_CONFIGURATION_FAILURE = 'FETCH_DEVICE_CONFIGURATION_FAILURE';

export const PATCH_CHANGE_LANGUAGE_CONFIGURATION_BEGIN = 'PATCH_CHANGE_LANGUAGE_CONFIGURATION_BEGIN';
export const PATCH_CHANGE_LANGUAGE_CONFIGURATION_SUCCESS = 'PATCH_CHANGE_LANGUAGE_CONFIGURATION_SUCCESS';
export const PATCH_CHANGE_LANGUAGE_CONFIGURATION_FAILURE = 'PATCH_CHANGE_LANGUAGE_CONFIGURATION_FAILURE';

export const PATCH_CHANGE_NOTIFICATIONS_CONFIGURATION_BEGIN = 'PATCH_CHANGE_NOTIFICATIONS_CONFIGURATION_BEGIN';
export const PATCH_CHANGE_NOTIFICATIONS_CONFIGURATION_SUCCESS = 'PATCH_CHANGE_NOTIFICATIONS_CONFIGURATION_SUCCESS';
export const PATCH_CHANGE_NOTIFICATIONS_CONFIGURATION_FAILURE = 'PATCH_CHANGE_NOTIFICATIONS_CONFIGURATION_FAILURE';

export const PUT_EMAILANDPASS_BEGIN = 'PUT_EMAILANDPASS_BEGIN';
export const PUT_EMAILANDPASS_SUCCESS = 'PUT_EMAILANDPASS_SUCCESS';
export const PUT_EMAILANDPASS_FAILURE = 'PUT_EMAILANDPASS_FAILURE';

export const PATCH_CHANGE_UNITS_CONFIGURATION_BEGIN = 'PATCH_CHANGE_UNITS_CONFIGURATION_BEGIN';
export const PATCH_CHANGE_UNITS_CONFIGURATION_SUCCESS = 'PATCH_CHANGE_UNITS_CONFIGURATION_SUCCESS';
export const PATCH_CHANGE_UNITS_CONFIGURATION_FAILURE = 'PATCH_CHANGE_UNITS_CONFIGURATION_FAILURE';

export const FETCH_USER_CONFIGURATION_BEGIN = 'FETCH_USER_CONFIGURATION_BEGIN';
export const FETCH_USER_CONFIGURATION_SUCCESS = 'FETCH_USER_CONFIGURATION_SUCCESS';
export const FETCH_USER_CONFIGURATION_FAILURE = 'FETCH_USER_CONFIGURATION_FAILURE';

export const FETCH_SUPPORT_BEGIN = 'FETCH_SUPPORT_BEGIN';
export const FETCH_SUPPORT_SUCCESS = 'FETCH_SUPPORT_SUCCESS';
export const FETCH_SUPPORT_FAILURE = 'FETCH_SUPPORT_FAILURE';

export const FETCH_SYNC_BEGIN = 'FETCH_SYNC_BEGIN';
export const FETCH_SYNC_SUCCESS = 'FETCH_SYNC_SUCCESS';
export const FETCH_SYNC_FAILURE = 'FETCH_SYNC_FAILURE';

export const FETCH_CREATE_CLUB_BEGIN = 'FETCH_CREATE_CLUB_BEGIN';
export const FETCH_CREATE_CLUB_SUCCESS = 'FETCH_CREATE_CLUB_SUCCESS';
export const FETCH_CREATE_CLUB_FAILURE = 'FETCH_CREATE_CLUB_FAILURE';

export const FETCH_DELETE_CLUB_BEGIN = 'FETCH_DELETE_CLUB_BEGIN';
export const FETCH_DELETE_CLUB_SUCCESS = 'FETCH_DELETE_CLUB_SUCCESS';
export const FETCH_DELETE_CLUB_FAILURE = 'FETCH_DELETE_CLUB_FAILURE';

export const FETCH_EDIT_CLUB_BEGIN = 'FETCH_EDIT_CLUB_BEGIN';
export const FETCH_EDIT_CLUB_SUCCESS = 'FETCH_EDIT_CLUB_SUCCESS';
export const FETCH_EDIT_CLUB_FAILURE = 'FETCH_EDIT_CLUB_FAILURE';

export const FETCH_LOAD_CLUB_BEGIN = 'FETCH_LOAD_CLUB_BEGIN';
export const FETCH_LOAD_CLUB_SUCCESS = 'FETCH_LOAD_CLUB_SUCCESS';
export const FETCH_LOAD_CLUB_FAILURE = 'FETCH_LOAD_CLUB_FAILURE';

export const ACCEPT_TERMS = 'ACCEPT_TERMS';
export const ACCEPTED_TERMS = 'ACCEPTED_TERMS';

export const FETCH_FILTER_CLUB_MEMBER_BEGIN = 'FETCH_FILTER_CLUB_MEMBER_BEGIN';
export const FETCH_FILTER_CLUB_MEMBER_SUCCESS = 'FETCH_FILTER_CLUB_MEMBER_SUCCESS';
export const FETCH_FILTER_CLUB_MEMBER_FAILURE = 'FETCH_FILTER_CLUB_MEMBER_FAILURE';

export const FETCH_FILTER_CLUB_ADMIN_BEGIN = 'FETCH_FILTER_CLUB_ADMIN_BEGIN';
export const FETCH_FILTER_CLUB_ADMIN_SUCCESS = 'FETCH_FILTER_CLUB_ADMIN_SUCCESS';
export const FETCH_FILTER_CLUB_ADMIN_FAILURE = 'FETCH_FILTER_CLUB_ADMIN_FAILURE';

export const FETCH_UPLOAD_CLUB_IMAGE_BEGIN = 'FETCH_UPLOAD_CLUB_IMAGE_BEGIN';
export const FETCH_UPLOAD_CLUB_IMAGE_SUCCESS = 'FETCH_UPLOAD_CLUB_IMAGE_SUCCESS';
export const FETCH_UPLOAD_CLUB_IMAGE_FAILURE = 'FETCH_UPLOAD_CLUB_IMAGE_FAILURE';

export const FETCH_FORGOT_PASSWORD_BEGIN = 'FETCH_FORGOT_PASSWORD_BEGIN';
export const FETCH_FORGOT_PASSWORD_SUCCESS = 'FETCH_FORGOT_PASSWORD_SUCCESS';
export const FETCH_FORGOT_PASSWORD_FAILURE = 'FETCH_FORGOT_PASSWORD_FAILURE';


export const FETCH_NOTIFICATION_BEGIN = 'FETCH_NOTIFICATION_BEGIN';
export const FETCH_NOTIFICATION_SUCCESS = 'FETCH_NOTIFICATION_SUCCESS';
export const FETCH_NOTIFICATION_FAILURE = 'FETCH_NOTIFICATION_FAILURE';

export const CLEAR_CLUBINFO = 'CLEAR_CLUBINFO';

export const FETCH_CLUB_INFO_BEGIN = 'FETCH_CLUB_INFO_BEGIN';
export const FETCH_CLUB_INFO_SUCCESS = 'FETCH_CLUB_INFO_SUCCESS';
export const FETCH_CLUB_INFO_FAILURE = 'FETCH_CLUB_INFO_FAILURE';
export const FETCH_CLUB_MEMBER_INFO = 'FETCH_CLUB_MEMBER_INFO';
export const FETCH_CLUB_MEMBER_INFO_SUCCESS = 'FETCH_CLUB_MEMBER_INFO_SUCCESS';
export const FETCH_CLUB_MEMBER_INFO_FAILURE = 'FETCH_CLUB_MEMBER_INFO_FAILURE';


export const FETCH_SUBSCRIPTION_BEGIN = 'FETCH_SUBSCRIPTION_BEGIN';
export const FETCH_SUBSCRIPTION_SUCCESS = 'FETCH_SUBSCRIPTION_SUCCESS';
export const FETCH_SUBSCRIPTION_FAILURE = 'FETCH_SUBSCRIPTION_FAILURE';

export const CHANGE_NOTIFICATION_BEGIN = 'CHANGE_NOTIFICATION_BEGIN';
export const CHANGE_NOTIFICATION_SUCCESS = 'CHANGE_NOTIFICATION_SUCCESS';
export const CHANGE_NOTIFICATION_FAILURE = 'CHANGE_NOTIFICATION_FAILURE';

export const PUT_UPDATINGINFO_BEGIN = 'PUT_UPDATINGINFO_BEGIN';
export const PUT_UPDATINGINFO_SUCCESS = 'PUT_UPDATINGINFO_SUCCESS';

export const ROUTE_PICKDEVICE = 'ROUTE_PICKDEVICE';
export const ROUTE_PICKDEVICE_DONE = 'ROUTE_PICKDEVICE_DONE';

export const SET_APP_CONNECTION_STATUS = 'SET_APP_CONNECTION_STATUS';

export const SET_ACTIVE_TRIPS_BOOLEAN = 'SET_ACTIVE_TRIPS_BOOLEAN';
export const SET_MASTER_LIST_TICKET_DATA = 'SET_MASTER_LIST_TICKET_DATA';

export const GET_MASTER_LIST_DATA = 'GET_MASTER_LIST_DATA';
export const VALIDATE_TICKET_FORM = 'VALIDATE_TICKET_FORM';
export const SEND_FORM_DATE = 'SEND_FORM_DATE';
export const GET_ACTIVE_TRIPS = 'GET_ACTIVE_TRIPS';
export const SET_USER_HAS_TRIP = 'SET_USER_HAS_TRIP';
export const SET_ACTIVE_TRIP = 'SET_ACTIVE_TRIP';
