export const FETCH_USER_GET_BEGIN = 'FETCH_USER_GET_BEGIN';
export const FETCH_USER_GET_SUCCESS = 'FETCH_USER_GET_SUCCESS';
export const FETCH_USER_GET_FAILURE = 'FETCH_USER_GET_FAILURE';

export const FETCH_USER_REGISTER_BEGIN = 'FETCH_USER_REGISTER_BEGIN';
export const FETCH_USER_REGISTER_SUCCESS = 'FETCH_USER_REGISTER_SUCCESS';
export const FETCH_USER_REGISTER_FAILURE = 'FETCH_USER_REGISTER_FAILURE';

export const LOGOUT = 'LOGOUT';
export const LOGOUTSUCCESS = 'LOGOUTSUCCESS';

export const SAVE_USER_SUBSCRIPTION = 'SAVE_USER_SUBSCRIPTION';
export const VALIDATE_USER_PAY = 'VALIDATE_USER_PAY';

export const SET_USER_STORE = 'SET_USER_STORE';
export const FETCH_USER_BEGIN = 'FETCH_USER_BEGIN';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';

export const ROUTE_LOGIN_BEGIN = 'ROUTE_LOGIN_BEGIN';
export const ROUTE_LOGIN_SUCCESS = 'ROUTE_LOGIN_FAILURE';
export const ROUTE_LOGIN_FAILURE = 'ROUTE_LOGIN_FAILURE';

export const FETCH_USER_LOGIN_BEGIN = 'FETCH_USER_LOGIN_BEGIN';
export const FETCH_USER_LOGIN_SUCCESS = 'FETCH_USER_LOGIN_SUCCESS';
export const FETCH_USER_LOGIN_FAILURE = 'FETCH_USER_LOGIN_FAILURE';

export const FETCH_USER_EVENT_BEGIN = 'FETCH_USER_EVENT_BEGIN';
export const FETCH_USER_EVENT_SUCCESS = 'FETCH_USER_EVENT_SUCCESS';
export const FETCH_USER_EVENT_FAILURE = 'FETCH_USER_EVENT_FAILURE';

export const FETCH_USER_PROFILE_BEGIN = 'FETCH_USER_PROFILE_BEGIN';
export const FETCH_USER_PROFILE_SUCCESS = 'FETCH_USER_PROFILE_SUCCESS';
export const FETCH_USER_PROFILE_FAILURE = 'FETCH_USER_PROFILE_FAILURE';

export const FETCH_IMAGE_PROFILE_BEGIN = 'FETCH_IMAGE_PROFILE_BEGIN';
export const FETCH_IMAGE_PROFILE_SUCCESS = 'FETCH_IMAGE_PROFILE_SUCCESS';
export const FETCH_IMAGE_PROFILE_FAILURE = 'FETCH_IMAGE_PROFILE_FAILURE';
export const VALIDATION_FAIL = '[register] fail validation form'

export const GO_GARMIN_BEGIN = 'GO_GARMIN_BEGIN';
export const GO_GARMIN_SUCCESS = 'GO_GARMIN_SUCCESS';

export const GO_SUUNTO_BEGIN = 'GO_SUUNTO_BEGIN';
export const GO_SUUNTO_SUCCESS = 'GO_SUUNTO_SUCCESS';

export const GET_API_DEVICES_BEGIN = 'GET_API_DEVICES_BEGIN';
export const GET_API_DEVICES_SUCCESS = 'GET_API_DEVICES_SUCCESS';
export const GET_API_DEVICES_FAILURE = 'GET_API_DEVICES_FAILURE';

export const GET_DEVICE_TRACKINGS = 'GET_DEVICE_TRACKINGS';
export const GET_DEVICE_TRACKINGS_SUCCESS = 'GET_DEVICE_TRACKINGS_SUCCESS';

export const GET_USER_EVENTS = 'GET_USER_EVENTS';
export const GET_USER_EVENTS_SUCCESS = 'GET_USER_EVENTS_SUCCESS';

export const POST_USER_TRACKINGS = 'POST_USER_TRACKINGS';
export const SAVE_USER_TRACKINGS = 'SAVE_USER_TRACKINGS';

export const GET_USER_PROGRESS = 'GET_USER_PROGRESS';
export const SAVE_USER_PROGRESS = 'SAVE_USER_PROGRESS';

export const GET_CURRENT_EVENT = 'GET_CURRENT_EVENT';
export const SAVE_CURRENT_EVENT = 'SAVE_CURRENT_EVENT';
export const ROUTING = 'ROUTING';
export const SAVE_FORM_REGISTER = 'SAVE_FORM_REGISTER';
export const GUARDAR_FORM_REGISTER = 'GUARDAR_FORM_REGISTER';
export const GUARDAR_FORM_REGISTER_FAILED = 'GUARDAR_FORM_REGISTER_FAILED';
export const UPDATE_FORM_REGISTER = 'UPDATE_FORM_REGISTER';
/* export const ID_TYPES = 'SAVE_TERMS_CONDITIONS'; */ //se llama ACCEPTED_TERMS esta en OTHERSTYPES
export const VALIDATE_FORM = 'VALIDATE_FORM';
export const GUARDAR_FORM = 'GUARDAR_FORM';
export const UPDATE_FORM = 'UPDATE_FORM';
export const POST_PHOTO = 'POST_PHOTO';
export const POST_USER = 'POST_USER';
//export const ID_TYPES = 'LOGIN_USER'; se usa el que ya estaba creado FETCH_USER_LOGIN_BEGIN
export const SAVE_USER = 'SAVE_USER';
export const SAVE_TOKEN = 'SAVE_TOKEN';
export const SAVE_ID_TYPE = 'SAVE_ID_TYPE';//ES DE ID TYPES
export const SAVE_RESIDENT_TYPE = 'SAVE_RESIDENT_TYPE';
export const SAVE_GENDER = 'SAVE_GENDER';
export const SAVE_CIVIL_STATE = 'SAVE_CIVIL_STATE';
export const SAVE_WORK_STATUS = 'SAVE_WORK_STATUS';
export const SAVE_REGISTER_SELECTORS = 'SAVE_REGISTER_SELECTORS';
export const SAVE_DOCUMENT_USER = 'SAVE_DOCUMENT_USER';
export const SAVE_USER_LOGIN = 'SAVE_USER_LOGIN';
export const SAVE_LOADER = 'SAVE_LOADER';
export const SAVE_COMPANY_TYPE = 'SAVE_COMPANY_TYPE';
export const SAVE_TRANSPORTATION_MODE = 'SAVE_TRANSPORTATION_MODE';
export const GET_STATIONS = 'GET_STATIONS';

export const EDITAR_PERFIL_USER = 'EDITAR_PERFIL_USER';
export const EDITAR_PERFIL_USER_OK = 'EDITAR_PERFIL_USER_OK';
export const RESET__PROFILE = 'RESET__PROFILE';
export const EDITAR_PHOTO_PERFIL_USER = 'EDITAR_PHOTO_PERFIL_USER';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const UPDATE_PASSWORD_OK = 'UPDATE_PASSWORD_OK';